### ISSUE TITLE
Restarting Name Server raises socket.error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by mkmoisen** [irmen/Pyro4#100]
I've found that around half the time, restarting the Name Server (either by hitting `CTRL+C` in a window that is running the Name Server, or by killing the Name Server process when it is controlled by `supervisord`) will result in the following error:

    socket.error: [Errno 98] Address already in use

When this error occurs, it takes about 30 seconds for the Name Server to release the socket.

This error does not occur all the time. Sometimes I can restart the server 10 times in a row without issue. Other times I will encounter this issue 10 times in a row.

Is there a way to prevent this?

**Comment by irmen** [comment]
What platform are you on? (OS/python version).   I can't reproduce this on windows and linux.

Anyway, there's the ``SOCK_REUSE`` config item that you can set to True, which will result in the SO_REUSEADDR socket option to be used on the sockets Pyro  creates.  Perhaps this helps

**Comment by mkmoisen** [comment]
I did some more investigating - this error doesn't get raised randomly like I had thought.

I am on RHEL6.4, Python 2.7.6, Jython 2.7.0, and am using Pyro 4.34 (on both Python and Jython). I uninstalled the latest version of Pyro in order to get it to work with Jython, but if I recall correctly, I had the same error.

To reproduce the error:

1) In one window, start the Name Server with `pyro4-ns`

2) In a second window, start a Pyro Server with code similar to the following:

    import Pyro4

    class Foo(object):
        def bar(self):
            print "baz"

    ns = Pyro4.locateNS()
    daemon = Pyro4.Daemon()
    uri = daemon.register(Foo()) # or just Foo if not using 4.34
    ns.register('test', uri)
    print 'ready'
    daemon.requestLoop()

3) In the first window, hit `CTRL+C` to stop the Name Server (Note that the Pyro server is still running)
Attempt to start the Name Server again with `pyro4-ns`. Thjis fails with

    socket.error: [Errno 98] Address already in use

and the name server cannot restart for roughly 30 seconds.

--------------

However, your suggestion worked. 

In the first window, prior to starting the Name Server, issue `export PYRO_SOCK_REUSE=True`, then start the Name Server with `pyro4-ns`. Tiurn on the Pyro Server in another window, and then CTRL+C and restart in the first window: no error.

Before I close this issue, is there any downside to having SOCK_REUSE set to True? If not, why is it defaulted to False?

Thanks for the help -- this was the last issue I had with Pyro. Thanks for this awesome library.

**Comment by irmen** [comment]
it's defaulting to false because that is the default socket behavior.
Changing SO_REUSEADDR opens the possibility of receiving some packets that are not meant for you. It's got to do with TCP protocol level timings. But I think in the context of Pyro it is safe to enable it if your system produces 'Address already in use' errors.    I'll think about enabling it in Pyro by default.

**Comment by irmen** [comment]
btw in commit fc5ae662510bd9ded4c99cbe33e22cb6ab1d1666 the option now defaults to ON -- let's see how things develop with that
