### ISSUE TITLE
Upgrading from Pyro, new methods

### ISSUE THREAD

**Issue by 33mhz** [irmen/Pyro4#101]
I'm trying to use OpenOPC with Pyro4 instead of Pyro, and am unfamiliar with either, in general. This is how it currently uses Pyro:

```
   import Pyro.core
   Pyro.core.initClient(banner = 0)
   server_obj = Pyro.core.getProxyForURI("PYROLOC://%s:%s/opc" % (host, port))
   return server_obj.get_clients()
```

I see in the docs that `Pyro.core.initClient()` is deprecated, and I don't see an equivalent `Pyro.core.getProxyForURI()`. Can you give an example of how to do this now?

**Comment by irmen** [comment]
Please read the Pyro documentation, it will teach you everything you need to know.
For your particular question here, see http://pythonhosted.org/Pyro4/upgrading.html#client-code-differences
It tells you that for creating proxies you can use the Proxy class constructor, pass in an URI or an uri string directly.    A simple example is here http://pythonhosted.org/Pyro4/intro.html#simple-example
The Pyro4 source code also comes with a myriad of example projects that show you how you can do things.
