### ISSUE TITLE
Logging Question

### ISSUE THREAD

**Issue by mkmoisen** [irmen/Pyro4#103]
Hi Irmen,

This isn't an issue, but I just wanted to bounce an idea off of you, or anyone else who has some insight into this. 

I would like to add some fine grained logging to my Pyro server. When any application or user gets a connection to my Pyro server, I would like to give that connection a unique ID, and log all messages during that session under this unique ID. In doing so, I would then be able to grep the log file for a single ID to get all related lines for that one session. The entire purpose of this would be to enabling filtering on the logs for all the steps that a user has gone through while having an active session with my Pyro server. The application that connects to the pyro server is responsible for creating a unique id and passing it to the session. That way, the application can log the ID, and from this ID I can search my log files.

This sounds nice to me, but I'm curious if there is a reason why this approach is generally not taken. I use the same approach for my REST APIs and for anything that I can log "as a session". If the application isn't session oriented, I just log the "normal" way, with one logger per module, and then it becomes impossible to track a single session's activities in the log file (assuming there are multiple connections at once).

Here is a code snippit that resembles my approach.

Foo is the actual pyro server. An application/user that wants to create a session asks Foo for a Bar, and Foo autoproxies the Bar object.  A Bar represents a single session and the user will perform actions on the Bar during this session. The build_logger creates a logger with a unique name, and the instance of foo will be assigned to this unique logger.

    def build_logger(id=None):
        # builds a logger with a unique id as its name
        # this permits each session to have its own logger, but all sessions log to same file
        if id is None:
            id = uuid.uuid4()
        logger = logging.getLogger(id)
        logger.setLevel(LOGGER_LEVEL)
        handler = logging.handlers.RotatingFileHandler(LOG_FILENAME,
                                                   maxBytes=10000000,  # 10000000
                                                   backupCount=10)  #
        # %(name) is used in formatter to discriminate between sessions in the log file
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        logger.addHandler(handler)
        return logger

        
    class Foo(object):
        # This is the actual pyro server
        # It creates a Bar object, autoproxies it as a pyro object, and the user then makes calls to the Bar object
        def bar(self, id=None):
            # When the user wants to create a new session to a Bar, he could pass in a unique ID
            # this way, the calling application can log the id, and I can find it in my logs.
            logger = build_logger(id)
            b = Bar(logger)
            self._pyroDaemon.register(b)
            return b
    class Bar(object):
        # this is an object that will be autoproxied by the Pyro server Foo
        # a call to Bar() by the pyro server represents a single session from some app or user 
        def __init__(self, logger):
            self.logger = logger
            self.logger.debug("New session created")
        def baz(self):
            try:
                self.logger.debug("Attempting to baz()"
                #....
            except Exception as ex:
                self.logger.exception("baz() Failure")
                raise ex
             else:
                 self.logger.debug("baz() Success")

    #....
    daemon = Pyro4.daemon()
    uri = daemon.register(Foo()) # Pyro3.43 
    ns.register("foo", uri)
    daemon.requestLoop()

**Comment by irmen** [comment]
Pyro only recently gained the concept of a call context that contains a correlation id (which can be set in your client code). Have you looked at it?  https://pythonhosted.org/Pyro4/tipstricks.html#client-information-on-the-current-context-correlation-id
Note that it's not tied to the server connection but rather sent from the client proxy. (the way connections are managed is determined by your daemon and the @expose parameters you might set on the Pyro classes)

You can extract the correlation id (or session id etc if you so wish to call it) from within your own server code (see the ``callcontext`` example).  And then use it in your own log statements.

Pyro itself doesn't use it yet in any of its own internal logging, which is not optimal. I'll have a look later at ways to possibly improve this. In the meantime can you comment on the possible use of the correlation id for your use case

**Comment by mkmoisen** [comment]
Unfortunately I'm using Pyro4.34 to get access to Jython, which doesn't have the current_context.

However, this gives me another idea, which would still be pertinent to later users of Pyro

When a session first calls for the Bar object, it can pass in an ID which is then associated to the instance of bar (Or, later users of Pyro would set Pyro4.current_context.correlation_id = uuid.uuid4()). Then, instead of each instance of bar having its own logger, there is only one logger for the entire module.  The only drawback is that I have to prepend each message in the call to log with "- {} -".format(self.id).

I can't seem to wrap my head around which one of these is better and why. I know that is is a bit strange to have each instance of the class have its own logger, but it prevents me from having to prepend the "- {} -".format(self.id) each time.

    # Only one instance of logger for the module, each Bar() uses this logger
    # eg, logger.debug(" - {} - message here".format(self.id))
    logger = logging.getLogger(__name__)
    logger.setLevel(LOGGER_LEVEL)


    class Foo(object):
        # This is the actual pyro server
        # It creates a Bar object, autoproxies it as a pyro object, and the user then makes calls to the Bar object
        def bar(self, id=None):
            # When the user wants to create a new session to a Bar, he could pass in a unique ID
            # this way, the calling application can log the id, and I can find it in my logs.
            b = Bar(id)
            # Later users of pyro would instead just do:
            # ctx = Pyro4.current_context.
            # b = Bar(ctx.correlation_id)
            self._pyroDaemon.register(b)
            return b
    class Bar(object):
        # this is an object that will be autoproxied by the Pyro server Foo
        # a call to Bar() by the pyro server represents a single session from some app or user 
        def __init__(self, id=None):
            if id is None:
                id = uuid.uuid4()
            self.id = id
            logger.debug(" - {} - New session created".format(self.id))
        def baz(self):
            try:
                logger.debug(" - {} - Attempting to baz()".format(self.id)
                #....
            except Exception as ex:
                logger.exception(" - {} - baz() Failure".format(self.id))
                raise ex
             else:
                 logger.debug(" - {} - baz() Success".format(self.id))

**Comment by irmen** [comment]
I'm about to close this as this is really a logging question, not a Pyro question. Or do you propose a change to Pyro's internal logging system as well?
