### ISSUE TITLE
Traceback lost?

### ISSUE THREAD

**Issue by Peque** [irmen/Pyro4#106]
Running a name server:

    python -m Pyro4.naming

Having the following `server.py`:

```python
import Pyro4


class Test(object):
    def test(self):
        return int('a')


if __name__ == '__main__':

    daemon = Pyro4.Daemon()
    ns = Pyro4.locateNS()
    uri = daemon.register(Test)
    ns.register("test", uri)

    print("Ready.")
    daemon.requestLoop()
```

And having the following `client.py`:

```python
import Pyro4


if __name__ == '__main__':

    proxy = Pyro4.Proxy("PYRONAME:test")
    proxy.test()
```

This code basically ends up executing `int('a')`, which in Python should raise:

    ValueError: invalid literal for int() with base 10: 'a'

The `ValueError` is raised when running `client.py`, however, the traceback looks like this:

```
Traceback (most recent call last):
  File "client.py", line 7, in <module>
    proxy.test()
  File "/home/peque/.miniconda3/envs/pyro4/lib/python3.5/site-packages/Pyro4/core.py", line 172, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/peque/.miniconda3/envs/pyro4/lib/python3.5/site-packages/Pyro4/core.py", line 427, in _pyroInvoke
    raise data
ValueError: invalid literal for int() with base 10: 'a'
```

Note that `client.py:7; proxy.test()` is represented, but there is no reference to `server.py:6; return int('a')`, which is the line in which the exception actually occurred.

Am I missing something or is this actually not supposed to happen?

Thanks for your help. :blush:

**Comment by irmen** [comment]
This is exactly what should happen. Your client code has no way whatsoever to know that it was executing certain python code on the server. All Pyro can do is replicate the exception *value* that was raised.

However not all is lost.

Pyro is smart enough to save the traceback that occurred on the server. Python is just not showing it to you by default. See https://pythonhosted.org/Pyro4/errors.html#remote-exceptions to read about the line of code you'll have to add to your client to display the remote traceback information as well. 

You can even show the values in the remote stack frames if you so desire (read the detailed traceback paragraph).

**Comment by Peque** [comment]
@irmen thanks your for your quick response and for the link! :blush:

I would still like to clarify something, if you don't mind.

The client code outputs this traceback:

```
Traceback (most recent call last):
  File "client.py", line 7, in <module>
    proxy.test()
  File "/home/peque/.miniconda3/envs/pyro4/lib/python3.5/site-packages/Pyro4/core.py", line 172, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/peque/.miniconda3/envs/pyro4/lib/python3.5/site-packages/Pyro4/core.py", line 427, in _pyroInvoke
    raise data
ValueError: invalid literal for int() with base 10: 'a'
```

However, when talking about remote-call exceptions, these two lines are, in my opinion, of no use:

```
  File "/home/peque/.miniconda3/envs/pyro4/lib/python3.5/site-packages/Pyro4/core.py", line 172, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/peque/.miniconda3/envs/pyro4/lib/python3.5/site-packages/Pyro4/core.py", line 427, in _pyroInvoke
    raise data
```

The important thing is:

```
Traceback (most recent call last):
  File "client.py", line 7, in <module>
    proxy.test()
ValueError: invalid literal for int() with base 10: 'a'
```

However, you are rising a `ValueError` with a stack trace which does not show where the actual `ValueError` ocurred. To me it seems like a mixed (but incomplete) local-remote stack trace.

I have two questions:

- Why wouldn't you want to show the remote stack trace by default? (i.e.: `Pyro4.util.getPyroTraceback()`)
- Would it be possible, and perhaps make sense for Pyro, to merge the traceback information to form something like this?:
```
Traceback (most recent call last):
  File "client.py", line 7, in <module>
    proxy.test()
  File "server.py", line 6, in test
    return int('a')
ValueError: invalid literal for int() with base 10: 'a'
```

Thanks again for your attention.

**Comment by irmen** [comment]
Because it requires a change to Python's default exception handler if you want that, and a library such as Pyro should not change these kind of global settings.
It's trivial if you want it; install the excepthook that is mentioned on the page I linked above. But you'll have to activate it yourself because it remains your choice to hook into this behavior:
```
import sys
import Pyro4.util

sys.excepthook = Pyro4.util.excepthook
```
and you're set.

You'll need the ``getPyroTraceback`` or the excepthook because the remote traceback is not in any way 'merged' into the regular traceback. It's added as some metadata on the exception value object, and you'll have to execute some code to extract it and print it.

**Comment by Peque** [comment]
Hi @irmen,

Pyro should not change Python's default exception handler, I agree. However I was thinking in something like this (may not be the best implementation as it is just a mock-up/idea):

```python
class Proxy(Pyro4.core.Proxy):
    def _pyroInvoke(self, methodname, vargs, kwargs, flags=0, objectId=None):
        try:
            return super()._pyroInvoke(methodname, vargs, kwargs, flags=flags, objectId=objectId)
        except:
            sys.stdout.write(''.join(Pyro4.util.getPyroTraceback()))
            sys.stdout.flush()
            raise
```

It will display the remote traceback by default without changing Python's default exception handler. The remote traceback will be of course displayed *before* the local traceback.

I know I can do this on my side, out of Pyro4, so I am not going to bother you more with this anymore. Just wanted to leave this idea in case it could be considered. :blush:

Thanks again for your help and for this project, which is great! :smile:

**Comment by irmen** [comment]
I don't fancy libraries printing arbitrary things to stdout/stderr either.

**Comment by gst** [comment]
just FYI : I have the same feeling/idea than @Peque  : 

_why wouldn't you want to show the remote stack trace information by default?_ 

with own Pyro logger.

this is somehow related to #215

**Comment by irmen** [comment]
@gst it is convenient I agree, but consider the arguments on the table already. Pyro is a generic library and as such it should not print arbitrary messages or interfere with global Python errorhandling. If you want this, you should do it in your application code itself.
Pyro provides some tools (the exception hook in util, the getPyroTraceback method or the possibility to create your own proxy subclass to customize the behavior like what Peque showed above)  to make this easier if your code wants it, but ultimately, it leaves it up to you to enable them in your own client application code.

**Comment by gst** [comment]
it is not plain / raw prints but it's by using logging facility that I'm talking about, which is done also for library code :)

**Comment by irmen** [comment]
@gst I don't understand? This discussion here is about the remote traceback.

**Comment by gst** [comment]
I meant to have something like this simply : 
```
class Proxy(Pyro4.core.Proxy):
    def _pyroInvoke(self, methodname, vargs, kwargs, flags=0, objectId=None):
        try:
            return super()._pyroInvoke(methodname, vargs, kwargs, flags=flags, objectId=objectId)
        except:
            logger.error("PYRO remote traceback:\n%s", ''.join(Pyro4.util.getPyroTraceback()))
            raise
```

but then I don't like that the local traceback is also returned by getPyroTraceback .. :/

**Comment by irmen** [comment]
@gst that's because the exception is raised on the local side (it's your local client code that encountered an error). This is what would happen if you were doing a normal python function call, and Pyro doesn't interfere with that. The special thing about Pyro is that there is a *remote* party involved, hence the special method / exception hook to retrieve that additional part of the error
