### ISSUE TITLE
Revert `66fb6a1`: "Avoid compatibility problems with PyPy + dill"

### ISSUE THREAD

**Issue by Peque** [irmen/Pyro4#109]
Dill was recently added as a [new serialization method in Pyro](https://github.com/irmen/Pyro4/pull/107/). However, [some ugly fixes where made](https://github.com/irmen/Pyro4/pull/107/commits/66fb6a10d81b794525d4f40510d29aa64e66ca10) to workaround PyPy+dill compatibility issues.

These fixes should be reverted as soon as Dill fixes its [PyPy compatibility issues](https://github.com/uqfoundation/dill/issues/73). It seems [there is a patch](https://github.com/uqfoundation/dill/pull/131) already that may fix those issues, but it has not being integrated in Dill yet.

I am subscribed to both threads in Dill, so I will update this issue with any relevant information.

**Comment by irmen** [comment]
Note that commit aa7a71532b99ce1b97c4617e6f8a28879db6a9fd extends these workarounds to add IronPython as well. It doesn't like dill either. 
This means we'll now probably get conflicts if we simply want to revert the pypy workaround. Not a big deal, it's not much code

**Comment by Peque** [comment]
@irmen Thanks. Fortunately you are right, it is not a lot of code, so it will be easy to revert anyway. I just wrote a message to Dill's developer to know if there is any work-in-progress or update in relation to PyPy compatibility.

**Comment by mmckerns** [comment]
The patch noted above is merged, and I've also fixed a number of the remaining compatibility issues.  There are still a few that I can see that remain, however, which I need to get back to soon.

I should note (I saw discussion in the original PR from @Peque) that you can `import dill` and then stop `dill` from overriding `pickle` -- that way, you can override things in a more piecemeal fashion if you like.
```
>>> import dill
>>> dill.extend(False)
```

**Comment by irmen** [comment]
any progress with dill? (sorry I haven't bothered to investigate myself).

**Comment by Peque** [comment]
@irmen yes, [there has been some progress](https://github.com/uqfoundation/dill/issues/73#issuecomment-223320477)! I will try to test the latest changes this week (did not find time before). :innocent:

**Comment by irmen** [comment]
awesome, thanks.

**Comment by Peque** [comment]
It seems the tests do not pass yet. 7 fails, detailed here:

https://gist.github.com/Peque/be752e1fa6f4e845ace9607d803fb0f7

They all end in the form:

```
[...]
  File "/usr/lib64/pypy-4.0.1/lib-python/2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/media/src/Pyro4/.tox/pypy/site-packages/dill/dill.py", line 1015, in save_wrapper_descriptor
    pickler.save_reduce(_getattr, (obj.__objclass__, obj.__name__,
AttributeError: 'function' object has no attribute '__objclass__'
```

@mmckerns Any ideas? :blush:

**Comment by mmckerns** [comment]
Aha… this appears to be an issue that is not tested in the main `dill` test suite, but is tested in `dill_bugs.py` which is a collection of known failure cases.  Apparently `dill` is failing in `pypy` in an unexpected way, and this case is replicating the errors you are seeing.  Let's move this to a new ticket in `dill` for this particular case.

**Comment by Peque** [comment]
@mmckerns Thanks. :heart:

I will keep an eye on that issue and try again when it is solved.

**Comment by irmen** [comment]
Ok. I don't think I'll wait for this for the upcoming Pyro release, it will (hopefully) land in the one after that.

**Comment by Peque** [comment]
@irmen Sure, go ahead. Let us hope it will be ready for the next release. :blush:

**Comment by irmen** [comment]
any progress on this front? 👷

**Comment by Peque** [comment]
@irmen I don't think so. I may try to contact Mike this weekend and propose him a deal: he works on this, I help him setting up CI in `dill` with `pytest` and Travis (I've done some initial coding and seems doable)... Don't know if he'll be interested, though. :sweat_smile:

**Comment by irmen** [comment]
okay thanks for the update!

**Comment by mmckerns** [comment]
I have not had time to resolve this issue yet, but you can track the progress here: (https://github.com/uqfoundation/dill/issues/175).  I may be able to get to it over the next week or so, and hopefully it's easy to solve.  Basically, I think the only compatibility issue I can see is with the `wrapper_descriptor`.

**Comment by Peque** [comment]
It seems there are some updates related to this:

https://github.com/uqfoundation/dill/issues/175

There is a discussion in PyPy's Bitbucket (where Armin Rigo himself has been very diligent and helpful):

https://bitbucket.org/pypy/pypy/issues/2464/getset_descriptor-cannot-access

So, hopefully, everything will be fixed and ready for the next PyPy and dill versions. :blush:

Thanks a lot, @mmckerns.

**Comment by irmen** [comment]
Nice to hear!

**Comment by mmckerns** [comment]
The latest builds of `pypy` and `dill` pass all tests that I have for `pypy` + `dill` compatibility.  You guys are probably better suited to further test this than I am.  Please report any issues you might find.

**Comment by irmen** [comment]
thanks 
it does require a new pypy version from what I understand (which one?).
I'm not sure yet if this is reason enough to keep the checks in place but make them know about the minimum pypy version required to make things work, or just assume it will be resolved externally.

**Comment by Peque** [comment]
@irmen Last commit in PyPy related to this issue is from an hour ago, so it will require next version (not-yet-tagged). I guess right now the only way to try this is with the PyPy latest development version. I haven't download it nor try it yet, though.

Maybe next week I'll find some time to download it and try it to see if everything is fixed. Regarding the "keep the checks in place" issue... I guess that is as you wish, you are the owner. :wink:

**Comment by mmckerns** [comment]
I have been testing against the `pypy` nightly builds, which are pretty easy to install and work with.

**Comment by irmen** [comment]
I suppose it is enough to add a warning in the docs that using dill will require a very recent pypy version with the needed changes to support it. And remove the workarounds from the code. That way we don't have to wait for an official release version and don't have to stick around with ugly version checks in the pyro code.  (unfortunately the checks for ironpython have to remain..)

**Comment by Peque** [comment]
@irmen Agree. Although maybe we should wait for an official `dill` and `pypy` releases. Otherwise Pyro4 tests will fail in Travis (unless we configure the `pypy` tests to be executed with a nightly build or something...). If there is no need to hurry this changes, I would rather wait. :wink:

PS: couldn't try the latest changes with `pypy` nightly builds (dependencies on libraries not available in my system: Fedora). I guess I could try with a containerized Ubuntu, but have not found the time yet.

**Comment by mmckerns** [comment]
A new `dill` release is imminent.  Should be out in a few days.

**Comment by irmen** [comment]
There's no need to hurry things. Although I don't know what pypy's release schedule is

**Comment by mmckerns** [comment]
No worries, it's a planned release.

**Comment by Peque** [comment]
@irmen They do not have a fixed schedule, I think, but it is usually each couple of months. This year there is no release yet, but last year there were in November, September, August, June, May, April, March... So I hope it wont take much longer to see a new release this year. :blush:

**Comment by irmen** [comment]
commit c6cf81c440f64aec5ab5cd5647643e5c46a5476e removes most of the platform checks with dill, in anticipation of the new releases

**Comment by Peque** [comment]
@irmen You may want to change `.travis` config file meanwhile (#145).

**Comment by irmen** [comment]
I noticed the new dill release came out recently, and indeed it fixes the issues with pypy. For Pyro's test suite, we don't even need the latest pypy release to successfully complete
