### ISSUE TITLE
A bug in Pyro4/socketutil.py 

### ISSUE THREAD

**Issue by kejiewei** [irmen/Pyro4#113]
Hi irmen,

When I run `python Pyro4/nsc.py list`, I got an error 

```Error: CommunicationError - cannot connect: unorderable types: NoneType() > float()```

With pdb debug, I find in Pyro4/socketutil.py:309, timeout may be None Type, and it causes error.

Please have a look, thanks!

**Comment by irmen** [comment]
Good catch. (note that max(int, None) results in said error since Python 3, while it used to work on Python 2)
