### ISSUE TITLE
Pyro4 depends on selectors34 module 

### ISSUE THREAD

**Issue by jmccormac01** [irmen/Pyro4#114]
I just tried installing Pyro4 on Windows 10 with pip and got the following when I tried importing it:

```python
ImportError: No module named selectors34
```

I installed selectors34 manually via pip and it then imported fine. There seems to be a missing dependency (under W10 at least).

**Comment by irmen** [comment]
How did you install Pyro4? The dependency is listed in requirements.txt (just as serpent is).
By using pip install pyro4 it comes automatically, otherwise, you could do pip install -r requirements.txt and it will be installed for you.

**Comment by jmccormac01** [comment]
I did install with pip and only serpent was installed. I just thought I'd point it out to you.

**Comment by irmen** [comment]
The way I added the dependency to the setup.py file wasn't working when creating a wheel (.whl) from it. After some digging around it seems the recommended way to have conditional dependencies is by using extras_require.  Changed this in the setup.py. 

Unfortunately this minor change does mean a new release.

So; it should be fixed; run `pip install --upgrade Pyro4` to get version 4.45 and you should be good to go
