### ISSUE TITLE
create a new serializer

### ISSUE THREAD

**Issue by zappfinger** [irmen/Pyro4#115]
Sorry to ask you here, but I found Freelist not clear on how to ask a question there. 
I am trying to make a remote connection to a SQLite database, but I get: 'TypeError: don't know how to serialize class <type 'sqlite3.Row'>. Give it vars() or an appropriate __getstate__'
So I wondered could I create my own serializer for this? 

Richard (zappfinger@gmail.com)

**Comment by irmen** [comment]
Freelist: you have to register as a subscriber over at http://www.freelists.org/list/pyro and then simply send emails to pyro@freelist.org, that's all there is to it

Your actual question:
You probably don't have to create a serializer. You can register converter functions, see http://pythonhosted.org/Pyro4/clientcode.html?highlight=serialization#changing-the-way-your-custom-classes-are-de-serialized

But the best thing to do is probably to avoid the problem altogether. Don't return custom classes directly, instead convert them into a more basic representation perhaps as a simple dict or list and return that instead.

What is the class it complains about anyway?
If it's something from numpy, also read this https://pythonhosted.org/Pyro4/tipstricks.html?highlight=numpy#pyro-and-numpy

**Comment by irmen** [comment]
Also, if you're able to modify the class in question, you can also simply do what the error message suggests: add an appropriate `__dict__` or `__getstate__` method to the class that returns the state. This makes its objects suddenly serializable by Pyro and your error will disappear
