### ISSUE TITLE
problem in daemon.shutdown()

### ISSUE THREAD

**Issue by brubbel** [irmen/Pyro4#121]
A thread seems to wait indefinitely when calling daemon.shutdown(), which worked previously correct on older versions of Pyro4 (installed with apt-get).
When shutdown_thread() at line 1009 in core.py is changed so that it is not called from a separate thread, shutdown() works as expected and the pyro server performs a clean exit.

Please note that I am running the daemon.requestLoop in a separate (non-daemon) thread**, while gui code runs in de main thread. The main thread calls daemon.shutdown at exit, which results in the following exception (after which one of the threads refuses to stop):

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 1012, in shutdown_thread
    self.transportServer.wakeup()
AttributeError: 'NoneType' object has no attribute 'wakeup'
---- program waits here ----

(**Daemon threads are abruptly stopped at shutdown.)

**Comment by irmen** [comment]
On what version of Pyro did it stil work?  The shutdown_thread thing has been in there for quite some time already.

Looking back at it now it does look ugly. Can you post some code that triggers the problem?

**Comment by irmen** [comment]
@brubbel could you please answer the question above?  
The code has been like this for a while now (329e26895988568985ac1012d865358802424d8e) so I'm hesitant to change it, since this is the first report about an issue with it.

**Comment by irmen** [comment]
Also, on what Python version are you running this?

**Comment by brubbel** [comment]
Since I recently got bitten again by the above problem, I remembered this issue. 
In attachment is a minimal sample program which shows the problem. 
(I also patched my version with the check against none described above, but that did not fix it.)


Pyro version: 4.45
Loaded from: /usr/local/lib/python2.7/dist-packages/Pyro4
Python version: CPython 2.7.6 (Linux, posix)
Protocol version: 48
Currently active configuration settings:
AUTOPROXY = True
BROADCAST_ADDRS = <broadcast>, 0.0.0.0
COMMTIMEOUT = 0.0
COMPRESSION = False
DETAILED_TRACEBACK = False
DILL_PROTOCOL_VERSION = -1
FLAME_ENABLED = False
HOST = localhost
JSON_MODULE = json
LOGFILE = None
LOGLEVEL = None
LOGWIRE = False
MAX_MESSAGE_SIZE = 0
MAX_RETRIES = 0
METADATA = True
NATHOST = None
NATPORT = 0
NS_BCHOST = None
NS_BCPORT = 9091
NS_HOST = localhost
NS_PORT = 9090
ONEWAY_THREADED = True
PICKLE_PROTOCOL_VERSION = 2
POLLTIMEOUT = 2.0
PREFER_IP_VERSION = 4
REQUIRE_EXPOSE = False
SERIALIZER = serpent
SERIALIZERS_ACCEPTED = set(['json', 'marshal', 'serpent'])
SERVERTYPE = thread
SOCK_NODELAY = False
SOCK_REUSE = True
THREADING2 = False
THREADPOOL_ALLOW_QUEUE = False
THREADPOOL_SIZE = 16
USE_MSG_WAITALL = True


[testpyroexit.txt](https://github.com/irmen/Pyro4/files/517585/testpyroexit.txt)

**Comment by irmen** [comment]
That's unfortunate that the issue persists. Could you please try again with the 4.48 version that I've just released? It contains some threading related changes, perhaps the issue is gone with that.

Anyway thanks for the sample program, i'll have a look at it soon.

**Comment by brubbel** [comment]
I'll check later next week, and come back with the results. Thanks!

**Comment by brubbel** [comment]
I tried with the latest version (4.48) from pip. The pyro daemon exits, but the following exception occurs:

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 1004, in requestLoop
    self.transportServer.loop(loopCondition=condition)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/socketserver/threadpoolserver.py", line 144, in loop
    self.events([self.sock])
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/socketserver/threadpoolserver.py", line 176, in events
    self.pool.process(job)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/socketserver/threadpool.py", line 105, in process
    raise PoolError("job queue is closed")
PoolError: job queue is closed
```

**Comment by brubbel** [comment]
The problem disappears when a time.sleep(1) is added at the exit of shutdown(). Should there be a way to either make this a blocking call, or to implement a mechanism that uses the join() method of the shutdown_thread object?

```
    def shutdown(self):
        """Cleanly terminate a daemon that is running in the requestloop."""
        log.debug("daemon shutting down")

        def shutdown_thread():
            time.sleep(0.05)
            self.__mustshutdown.set()
            if self.transportServer:
                self.transportServer.wakeup()
                time.sleep(0.05)
            self.close()
            self.__loopstopped.wait(timeout=5)  # use timeout to avoid deadlock situations
            log.info("daemon %s shut down", self.locationStr)

        # We do the actual shutdown from a separate thread so that any Pyro method
        # that may be calling this, can return its response normally without directly
        # severing the socket and causing a ConnectionClosedError on the proxy.
        thread = threadutil.Thread(target=shutdown_thread)
        thread.start()
        **time.sleep(1)**
```

**Comment by irmen** [comment]
I don't like the shutdown call to become blocking when some thread remains to hang. I think I prefer adding a small time.sleep() in it.   I'll think about this.

Also-- is the problem present when you use the multiplex server in your test suite?

**Comment by brubbel** [comment]
Starting with `Pyro4.config.SERVERTYPE = "multiplex"` seems to work. I'll try this.
Adding the small sleep doesn't seem a solid solution to me, as you rely on the shutdown_thread finishing before the main thread just based on a delay.

**Comment by irmen** [comment]
Looking back at 329e26895988568985ac1012d865358802424d8e I'm wondering now if it was even a good idea to do it like this.  In hindsight, you probably never will want a Pyro proxy to shutdown a daemon anywa.  So; perhaps the problem disappears altogether when shutdown is no longer creating a thread. I'll explore a bit see if I can get this thing reproduced on my system

**Comment by irmen** [comment]
Right, out it went that thread. Can you test if 8aa836c5eb6b426539da8d0eeb66e413b3c13c86 fixes the issue on your end?

**Comment by brubbel** [comment]
This fixes the issue.
Setting Pyro4.config.SERVERTYPE = "multiplex" also was a possible solution.

**Comment by irmen** [comment]
I don't think it is worth it at this time to pursue this further. Glad it is resolved. Thanks for testing.
