### ISSUE TITLE
Default instance mode is not 'session'

### ISSUE THREAD

**Issue by TheLordOfTheVoid** [irmen/Pyro4#123]
I am exposing a class with the Pyro4.expose decorator, with no arguments. According to the docs this should expose the class using the 'session' instance mode. However, only one instance of the class is created and used, even with multiple sessions. This is also shown in the log: 

`[2016-08-06 10:56:38.408,Pyro4.core,DEBUG] exposing all members of <class '__main__.TestClass'>, instancemode single, instancecreator None.`

I have attached the log and a script that reproduces the issue.

[test_server.zip](https://github.com/irmen/Pyro4/files/404942/test_server.zip)

**Comment by irmen** [comment]
With your code as provided in the zip file I cannot reproduce what you're seeing. Are you sure you included the exact same code that generated the log file?

**Comment by TheLordOfTheVoid** [comment]
I included the wrong one, this should reproduce the issue 
[test_server.zip](https://github.com/irmen/Pyro4/files/405022/test_server.zip)
