### ISSUE TITLE
Multithreaded calls of pyroInvoke and pyroConnLock, and releasing proxies in-between

### ISSUE THREAD

**Issue by onnokort** [irmen/Pyro4#125]
Hi,

I think I found a threading bug in Pyro. In my code (unfortunately, I have no test case yet to reproduce), the following, occasional error from Pyro bubbles up:

```
  File "/home/user/.local/lib/python2.7/site-packages/Pyro4/core.py", line 171, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/Pyro4/core.py", line 405, in _pyroInvoke
    self._pyroConnection.send(msg.to_bytes())
AttributeError: 'NoneType' object has no attribute 'send' 
```

Pyro version: 4.40

Here is my suspicion on what happens: I have several threads working on the same pyro objects, and some of them might release the object after using it, to avoid clogging up connection slots on the server side.
In Pyro's core.py, the _pyroInvoke() method checks whether _pyroConnection is None  and if so, reconnects.

However, the pyroConnLock is not acquired, which means that until the offending line above is reached, some other thread might release the connection again without knowledge of the pyroInvoke method.

**Comment by irmen** [comment]
Is the issue still present in the current Pyro version? 

In the meantime, don't eagerly release your proxy if it is still being used by other threads.

**Comment by onnokort** [comment]
That was quick. Cool, thank you!
