### ISSUE TITLE
integrate zeroconf?  (avahi/bonjour)

### ISSUE THREAD

**Issue by irmen** [irmen/Pyro4#126]
https://github.com/jstasiak/python-zeroconf

can we register pyro services with zeroconf instead of a pyro name server?

and resolve them as well ofcourse.

Perhaps by introducing a new magic protocol name PYROZCONF:blah  ?

**Comment by irmen** [comment]
initial exploratory test is a bit meh;
- can't get any of the bonjour services hosted on my mac to be discovered from a remote windows or linux host.  A bonjour discovery tool for windows *does* list them
- it does work on the mac itself and another remote mac

**Comment by irmen** [comment]
decided not to pursue this any further.

**Comment by carandraug** [comment]
Do you have any code used for the initial test that you could share? I would like to pursue this further.

We have Pyro objects being served from multiple systems on a network. At any time, any of them might not be available so we would like systems to be able to discover what is available. We don't have a separate system that could be always on and be used as pyro nameserver. Hence why we are investigating pyro zeroconf.

**Comment by irmen** [comment]
@carandraug No I'm sorry, I never saved the initial experiment anywhere. In any case, it wasn't integrated in Pyro *at all* at that point, so I highly doubt it would be useful anyway.

I have been thinking a little bit about making the name server pluggable (that is, make the lookup calls pluggable so you can plug in your own resolver solution into it-- which could be something that taps into bonjour if we could get that working) Nothing serious atm though
