### ISSUE TITLE
Does pickle serialization work in 4.47?

### ISSUE THREAD

**Issue by miiza** [irmen/Pyro4#130]
Excerpt from config documentation:

config item | type | default | meaning
------------ | ------------- | ------------ | -------------
SERIALIZERS_ACCEPTED | set | json,marshal, serpent | The wire protocol serializers accepted in the server/daemon. Use comma separated string for initial config, will be a set after initialization.

So, I add this row to my source code:

`Pyro4.config.SERIALIZERS_ACCEPTED = "json, marshal, serpent, pickle"`

But get this error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/Pyro4/util.py", line 588, in get_serializer
    return _serializers[name]
KeyError: 'j'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "g_term_server.py", line 941, in <module>
    daemon = Pyro4.Daemon(port=3000)
  File "/usr/local/lib/python3.4/dist-packages/Pyro4/core.py", line 919, in __init__
    self.__serializer_ids = {util.get_serializer(ser_name).serializer_id for ser_name in Pyro4.config.SERIALIZERS_ACCEPTED}
  File "/usr/local/lib/python3.4/dist-packages/Pyro4/core.py", line 919, in <setcomp>
    self.__serializer_ids = {util.get_serializer(ser_name).serializer_id for ser_name in Pyro4.config.SERIALIZERS_ACCEPTED}
  File "/usr/local/lib/python3.4/dist-packages/Pyro4/util.py", line 590, in get_serializer
    raise Pyro4.errors.SerializeError("serializer '%s' is unknown or not available" % name)
Pyro4.errors.SerializeError: serializer 'j' is unknown or not available

If I changed the row to a list, it works fine:

Pyro4.config.SERIALIZERS_ACCEPTED = ["json", "marshal", "serpent", "pickle"]

So, is it a mistake in documentation? Should I enter it as a list?

Another problem is that NameServer doesn't work with pickle serialization. I have exported and restarted but it still doesn't work:

```
export PYRO_SERIALIZERS_ACCEPTED=serpent,json,marshal,pickle
pyro4-ns
```
I got rid of Name Server and it works directly fine.

**Comment by irmen** [comment]
Regarding SERIALIZERS_ACCEPTED;  the datatype of that config item is a *set*, which it also says in the documentation.  If you use a string it will iterate over the characters in the string which obviously doesn't work.  So yeah, you should use a list (or set, rather).

Regarding the name server: you're doing something wrong, it works as you wrote. You don't say what it is that "doesn't work". Have you enabled logging and checked if your options are recognized properly?

**Comment by miiza** [comment]
Regarding SERIALIZERS_ACCEPTED: In the **meaning** column is said: "**Use comma separated string for initial config**, _will be a set after initialization._".

Regarding the name server: How should I enable logging? I know it takes secure serializers but does not take pickle. Now I am getting this exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/Pyro4/naming.py", line 526, in locateNS
    proxy._pyroBind()
  File "/usr/local/lib/python3.4/dist-packages/Pyro4/core.py", line 371, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "/usr/local/lib/python3.4/dist-packages/Pyro4/core.py", line 510, in __pyroCreateConnection
    raise errors.CommunicationError(error)
Pyro4.errors.CommunicationError: connection rejected, reason: message used serializer that is not accepted: 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g_term_server.py", line 941, in <module>
    ns = Pyro4.locateNS()
  File "/usr/local/lib/python3.4/dist-packages/Pyro4/naming.py", line 533, in locateNS
    raise e
Pyro4.errors.NamingError: Failed to locate the nameserver

```
I have checked exported vars in shell and it is ok there. I don't know what could be broken in my environment. But it is not a problem for me, I can use it without name server. I just wanted to let you - for the case that somebody wanted to use it.

**Comment by irmen** [comment]
Fair enough, I'll clarify the meaning text a bit.  It assumes you're setting an environment variable as 'initial config' but I agree it can be a bit misleading.

The NS really does work with pickle, if you set that in SERIALIZERS_ACCEPTED. It's no different than any other Pyro server in this regard.   Info about logging is in the manual. Try this in one shell:

    $ export PYRO_LOGLEVEL=DEBUG
    $ export PYRO_LOGFILE={stderr}
    $ export PYRO_SERIALIZERS_ACCEPTED=marshal,json,serpent,pickle
    $ pyro4-ns

And observe that it prints the four serializers as accepted, including pickle.
In another shell:

    $ export PYRO_SERIALIZER=pickle
    $ pyro4-nsc list

And it will print the contents of the name server just fine.

If it still doesn't work you're probably running another nameserver somewhere that isn't configured to accept pickle.

**Comment by miiza** [comment]
Regarding 'initial config': Aha! You meant **operating system** environment!

Regarding the Name Server problem: I am running only one NS, that is OK. But it is necessary to export in shell not only PYRO_SERIALIZERS_ACCEPTED, but PYRO_SERIALIZER too! 

`export PYRO_SERIALIZER=pickle`

Without that, setting it in client python only will not help. It must be stated on both places. And it is not stated in documentation: see https://pythonhosted.org/Pyro4/nameserver.html#nameserver-pickle There is stated only PYRO_SERIALIZERS_ACCEPTED export necessary.

Could you add this info to the docs? It will really help people, I spent a lot of time trying to get it up.

Anyway, Pyro is a fantastic piece of software. It's a hidden gem. I am really excited that I have discovered it. Great job!

**Comment by irmen** [comment]
That should not be happening. Have you tried my suggestion above? It works fine on my machine without having to set PYRO_SERIALIZER on the name server process.  A Pyro server can always *reply* to any serializer protocol that it received (if it is in PYRO_SERIALIZERS_ACCEPTED), without the need to set PYRO_SERIALIZER.     This also holds for the name server.     If you still have the issue can you describe *exactly* what you are running and how? And where the error occurs?

**Comment by miiza** [comment]
I started from scratch and now it works perfectly. It means that I made some chaos during beginner experimenting with this technology and then made bad conclusions. 

I am sorry that I was wasting your time. Thank you very much!

**Comment by irmen** [comment]
I am glad that you got it working.  And there's no problem with asking things if they are unclear, at least one improvement in the docs has come out of this!
