### ISSUE TITLE
Migrate documentation to readthedocs.org

### ISSUE THREAD

**Issue by Peque** [irmen/Pyro4#132]
This is not really an issue, rather a suggestion.

I was recently looking for ways to publish the documentation of a [Python project I am developing](https://github.com/opensistemas-hub/osbrain), which uses Pyro, by the way. I found [Read the Docs](https://readthedocs.org/) and I think it is the best alternative.

Pros:
- Automatically build documentation whenever a new commit is pushed or a new release tagged (simple setup with GitHub). No need to manually build and upload to `pythonhosted.org`.
- Versions of the documentation are easily browsable. See for example [the lower-left corner, where you can find a green `v: stable` text](https://osbrain.readthedocs.io/en/stable/). You can change the version displayed from there.
- You can, of course, set a default version for the documentation, which usually is the "stable" version (last tagged version).
- [Read the Docs is a free software project](https://github.com/rtfd/readthedocs.org), so you can even deploy it your own server (if you needed/wanted to at some point).

Cons:
- Requires some time (a couple of minutes to create and account and setup a new project). I could help with that if you want to (although that requires some permissions to edit the integrations/services in the project settings).
- Could require, at some point, deprecating the documentation at `pythonhosted.org`. This is not mandatory, though, documentation could be found in both sites, although in that case, you would still need to manually update the docs to `pythonhosted` on each release... In case you wanted to deprecate the current documentation URLs at some point, I can share with you a simple HTML template page which has an HTML redirection to Read the Docs and a JavaScript redirection as well, so 99.9% of browsers should redirect to the new documentation automatically.

Whether or not this could be interesting for you, I don't know. Just wanted to let you know. In my opinion, pros win cons in this case.

**Comment by irmen** [comment]
Thanks for the suggestion, I'll have a look at it when doing the next release.   I have started to notice some problems with my current release workflow (the automatic upload of docs via setup.py upload_docs has stopped working somehow) so either I'm inclined to look into fixing that setuptools command or perhaps indeed moving to another doc hoster.   I'm pretty happy with pythonhosted so far though: it is no-nonsense, and works with setuptools upload  (well, it used to)

Do you know if you can you upload existing, older versions of the docs to readthedocs?

**Comment by Peque** [comment]
> Do you know if you can you upload existing, older versions of the docs to readthedocs?

Read the Docs can build all releases automatically, yes. It will build documentation versions based on the release tags in your Git project.

Even if you finally decide not to use Read the Docs ever, you might want to try it now just to see how it works or if you like it. The setup really only takes a couple of minutes. :wink:

**Comment by irmen** [comment]
I've set it up!

http://pyro4.readthedocs.io

**Comment by Peque** [comment]
@irmen Awesome! :blush:
