### ISSUE TITLE
Uncaught exception if client disconnects from multiplex server

### ISSUE THREAD

**Issue by gitj** [irmen/Pyro4#134]
Sorry I don't have a short piece of code to demonstrate this error, but I think it should be clear from looking at the code.
This line:
https://github.com/irmen/Pyro4/blob/master/src/Pyro4/socketserver/multiplexserver.py#L162
raised `error: [Errno 107] Transport endpoint is not connected`
when the client was disconnected.
So I think this possibility needs to be caught when trying to getpeername.

**Comment by irmen** [comment]
How did the client disconnect? Was it forcefully, did the network get interrupted, or was it a clean disconnect?

**Comment by gitj** [comment]
It was a forceful disconnect, the client process was killed. I am having trouble reproducing the error because I changed my architecture a bit to avoid the issue, but since getpeername can throw an exception and this exception occurs when trying to log another exceptional condition, it seems like it definitely needs to be caught and dealt with in any case.

**Comment by irmen** [comment]
Agreed, I'll have a look
