### ISSUE TITLE
Request-processing thread throws RuntimeError attempting Daemon.shutdown() or Daemon.close()

### ISSUE THREAD

**Issue by evandeaubl** [irmen/Pyro4#137]
We have an application where a Pyro Daemon object receives a remote Pyro request to shutdown (we are using the threadpool socketserver). As part of processing that request, the receiver calls shutdown() on the Daemon to stop any further requests. This worked previous to 4.49, but with the change in 4.49 to process the shutdown() in-thread, the thread attempts to join() itself, causing a RuntimeError.

From a read of the code, calling Daemon.close() from a request-processing thread would have the same issue. It also appears this would only happen with the threadpool socketserver, because the multiplex version doesn't have any join() calls.

**Comment by irmen** [comment]
I'm unsure what you are hinting at, do you mean the join() calls in the close method of threadpool.py? Also, can you provide some code that reproduces the issue.

**Comment by irmen** [comment]
The obvious code like below, works just fine for me. Can you supply some code that shows the problem?

```
import Pyro4

class ShutdownTest:
    @Pyro4.expose
    def shutdown(self):
        print("server shutting down")
        self._pyroDaemon.shutdown()
        print("shutdown done")

Pyro4.Daemon.serveSimple({
    ShutdownTest: "test.shutdown"
}, ns=False)

```

**Comment by evandeaubl** [comment]
Hmm, that seems like that should have tripped it. I'm out of the office so I don't have the code reproducing the failure available to me; I'll get you a reproducing test case on Monday.

**Comment by irmen** [comment]
any luck on composing the test case yet?

**Comment by evandeaubl** [comment]
Tore myself away from other work to finally get this. Looks like this is coming from the fact that we construct a `Daemon`, and supply that to `serveSimple`:

```python
import Pyro4

class Server(object):
    @Pyro4.expose
    def shutdown(self):
        self._pyroDaemon.close()

daemon = Pyro4.Daemon('localhost', 5000)
Pyro4.Daemon.serveSimple({
    Server: "server",
}, daemon=daemon, ns=False)
```

This fails with `RuntimeError: cannot join current thread` when `Server.shutdown()` is called remotely.

**Comment by irmen** [comment]
thanks I'll have a look.

**Comment by irmen** [comment]
Hm, the problem does not occur when I am running the server using Python 3.
What Python version and Operating system are you using?

**Comment by evandeaubl** [comment]
Python 2.7.9 (self-built) on CentOS 6.8.

**Comment by irmen** [comment]
I'm puzzled by my analysis results so far:

* crash doesn't occur when running python 3. (might be another reason to upgrade ;-) )
* creating your own daemon is not causing the issue, but the following is:
* on windows the problem occurs when binding on ``host=""`` (you can pass this as parameter to ``serveSimple``  and not on ``host="localhost"``
* ...unless on OSX or Linux, then it only occurs when binding on ``host="localhost"`` and not on something else.

😕

**Comment by irmen** [comment]
By the way, calling ``daemon.shutdown()`` rather than ``daemon.close()`` is preferred, as it also tries to cleanly break out of the running requestloop first, rather than dropping everything immediately.

**Comment by evandeaubl** [comment]
Thanks for the fix! And if it were my choice, we would have been using Python 3 for years... 🙄

**Comment by irmen** [comment]
Don't worry Pyro4 will keep working on Python 2.7 for the forseeable future.
It will just work better on Python 3.x 😉
