### ISSUE TITLE
Thread vs. multiplex NameServer behavior

### ISSUE THREAD

**Issue by Peque** [irmen/Pyro4#164]
I have some code that works fine when using `Pyro4.config.SERVERTYPE = 'multiplex'` but fails when using `Pyro4.config.SERVERTYPE = 'thread'`. So I though I would ask here.

Notes:

- I have my own `NameServer` class, which is the same `Pyro4.naming.NameServer` only adding a new method `.shutdown()` that changes an attribute `shutdown_daemon` from `False` to `True` when executed.
- I have a `NameServerProcess` class, which is a `multiprocessing.Process` that, when started, runs a `NameServerDaemon`'s `.requestLoop()`. Note that the parameter to the `.requestLoop` is "monitoring" changes in the attribute `shutdown_daemon` previously mentioned.
- I then have a `NSProxy` class that acts as a `Pyro4.core.Proxy` to the `NameServer` object, so that I can execute the method `.shutdown()`.
- I have a function which starts a `NameServerProcess` binding the daemon to a random (available) port.

Then, what I do is:

1. Start a `NameServerProcess` binding to a random address
1. Create a `NSProxy` to the `NameServer` object.
1. Call the remote `.shutdown()` method from the proxy.

This is working as expected when `Pyro4.config.SERVERTYPE` is set to `multiplex`. However, when I change it to `thread`, it blocks (never gets out of the `.requestLoop()` call, it seems.

Do you have any idea about why could this be happening? Thanks in advance for any help or advice you could give me. :blush:

Here is the code I am using, reduced as much as I could to represent this case:

```python
import os
import time
import random
import multiprocessing

import Pyro4
Pyro4.config.SERVERTYPE = 'multiplex'

from Pyro4.naming import BroadcastServer
from Pyro4.errors import NamingError


@Pyro4.expose
class NameServer(Pyro4.naming.NameServer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.shutdown_daemon = False

    def shutdown(self):
        """
        Shutdown the name server. All agents will be shutdown as well.
        """
        self.shutdown_daemon = True


Pyro4.naming.NameServer = NameServer


class NameServerProcess(multiprocessing.Process):
    """
    Name server class. Instances of a name server are system processes which
    can be run independently.
    """
    def __init__(self, addr=None):
        super().__init__()
        if isinstance(addr, int):
            addr = '127.0.0.1:%s' % addr
        self.addr = addr
        self.host = addr.split(':')[0]
        self.port = int(addr.split(':')[1])
        self.uri = None
        self.queue = multiprocessing.Queue()

    def run(self):
        try:
            self.daemon = Pyro4.naming.NameServerDaemon(self.host, self.port)
        except Exception:
            self.queue.put('ERROR')
            return
        self.queue.put('STARTED')
        self.uri = self.daemon.uriFor(self.daemon.nameserver)
        self.host = self.uri.host
        self.port = self.uri.port
        internal_uri = self.daemon.uriFor(self.daemon.nameserver, nat=False)
        bcserver = None
        hostip = self.daemon.sock.getsockname()[0]
        # Start broadcast responder
        bcserver = BroadcastServer(internal_uri)
        print("Broadcast server running on %s" % bcserver.locationStr)
        bcserver.runInThread()
        print("NS running on %s (%s)" % (self.daemon.locationStr, hostip))
        print("URI = %s" % self.uri)
        try:
            self.daemon.requestLoop(
                lambda: (not self.daemon.nameserver.shutdown_daemon)
            )
        finally:
            self.daemon.close()
            if bcserver is not None:
                bcserver.close()
        print("NS shut down.")

    def start(self):
        os.environ['OSBRAIN_NAMESERVER_ADDRESS'] = str(self.addr)
        super().start()
        status = self.queue.get()
        if status == 'STARTED':
            return
        raise RuntimeError('An error occured while creating the daemon!' +
                           '\n===============\n'.join(['', status, '']))


class NSProxy(Pyro4.core.Proxy):
    """
    A proxy to access a name server.

    Parameters
    ----------
    nsaddr : SocketAddress, str
        Name server address.
    timeout : float
        Timeout, in seconds, to wait until the name server is discovered.
    """
    def __init__(self, nsaddr=None, timeout=3):
        if not nsaddr:
            nsaddr = os.environ.get('OSBRAIN_NAMESERVER_ADDRESS')
        nshost = nsaddr.split(':')[0]
        nsport = int(nsaddr.split(':')[1])
        # Make sure name server exists
        Pyro4.locateNS(nshost, nsport)
        ns_name = Pyro4.constants.NAMESERVER_NAME
        super().__init__('PYRONAME:%s@%s:%d' % (ns_name, nshost, nsport))


def random_nameserver_process(host='127.0.0.1', timeout=3.):
    """
    Start a random NameServerProcess.

    Parameters
    ----------
    host : str, default is '127.0.0.1'
        Host address where the name server will bind to.

    Returns
    -------
    NameServerProcess
        The name server process started.
    """
    t0 = time.time()
    exception = TimeoutError('Name server starting timed out!')
    while True:
        try:
            # Bind to random port
            port = random.randrange(10000, 20000 + 1)
            nameserver = NameServerProcess('%s:%s' % (host, port))
            nameserver.start()
            return nameserver
        except RuntimeError as error:
            exception = error
        if time.time() - t0 > timeout:
            raise exception


if __name__ == '__main__':

    ns = random_nameserver_process()
    nsproxy = NSProxy(ns.addr)
    nsproxy.shutdown()
```

**Comment by irmen** [comment]
Try setting COMMTIMEOUT to a value >0. I think the server is hanging in a socket.accept() call that runs in a thread, without having any form of timeout configured. This means it cannot be (reliably) aborted.

When using multiplex, Pyro's using the POLLTIMEOUT inside the requstloop. This means it will cleanly abort after a few seconds if told to do so.

You may also try to invoke Daemon.shutdown() instead of just setting a loop condition. This method tries to interrupt a running server (even the threaded one)

**Comment by Peque** [comment]
Thanks, it works fine with `Daemon.shutdown()`. However, when I use it with the `multiplex` server, it really takes some time to shutdown (i.e.: a couple of seconds). Is that expected? The `thread` server shuts down quickly.

For now, I have just added an if-else clause (if multiplex, don't call `shutdown()`, else do call it).

**Comment by irmen** [comment]
I don't know exactly. I think it has something to do with the fact that the selectors module doesn't have an ERROR event condition you can select on (this is quite unfortunate because the select() call can trigger on error conditions).  It seems the way the shutdown method is trying to trigger the selector to exit te loop isn't really working. I don't know of a better way right now.

Try setting POLLTIMEOUT to a smaller value if it really bothers you?

**Comment by Peque** [comment]
@irmen Thanks a lot, you can close this issue. Actually what I was interested in was the `thread` server implementation, and works fine with `Daemon.shutdown()`, so nothing really bothers me anymore. :blush:

**Comment by irmen** [comment]
I'm glad it's working because for the threaded server the shutdown method is also a bit of a hack 😉
