### ISSUE TITLE
handling synchronization and race condition

### ISSUE THREAD

**Issue by hsgodhia** [irmen/Pyro4#165]
In one of the example codes for the bank scenario `Pyro4/examples/banks/banks.py` 
I noticed that in the `withdraw` function for `RestrictedAccount` which is ideally supposed to prevent over withdraws and negative balance, would run into race conditions when the client is multithreaded and concurrently access the bank object for withdrawals (using different proxies, no proxysharing). How can this be prevented, does pyro4 support locks? if not how does one use python lock, rlock primitives on remote objects defined in pyro of `@Pyro4.behavior(instance_mode="single")` behavior

**Comment by irmen** [comment]
Pyro4 can't really help you with this. Actually, it's no different from concurrent access to a shared object in regular Python! (not using Pyro, I mean) -- you'll have to create a locking system yourself there as well to guarantee thread safety.

Pyro does provide you with the behavior mode as you already discovered, and you can vary the servertype.  Please read http://pythonhosted.org/Pyro4/servercode.html#server-types-and-concurrency-model  for more details.

If you are using a threaded server and *not* a per-call instance behavior mode, you are prone to concurrency issues. It is the safest to create a locking mechanism in your Pyro object then to protect the shared resources. Again, how you solve this is not different from how you do that in regular python multithreaded code.
