### ISSUE TITLE
Importing Pyro4 into IronPython crashes Unity3D process

### ISSUE THREAD

**Issue by marccrobbins** [irmen/Pyro4#174]
I have been using Pyro4 as means to interpret IronPython to Python to be able to communicate between Unity3D and Python.  

Everything worked fine until recently, I even downgraded Pyro4 to see if it was version specific. It is not. 

The crash only happens when I try to import Pyro4 into a .py file. With it excluded, I can run my processes(without Pyro connection) and Unity continues working as expected. 

I found something about Pyro possibly not liking more than 15 threads for some reason. Is this true? Is there a way to get around this?

**Comment by irmen** [comment]
This is way too little info to go by. At least post a full error traceback please!

Regarding the number of threads: no, the default limit has been 40 for a while now.  See
http://pythonhosted.org/Pyro4/config.html    on configurable options to change this.

**Comment by marccrobbins** [comment]
[error.txt](https://github.com/irmen/Pyro4/files/1045336/error.txt)

Here is an error log from the crash.

**Comment by marccrobbins** [comment]
The interesting thing is that the crash only happens when i import Pyro4.

**Comment by irmen** [comment]
I was hoping for a normal Python stacktrace. The error you posted looks like a low level technical crash dump from Unity itself and is unrelated to Pyro (or even Python).

If importing a pure python package (what Pyro is) can let it crash that severely I strongly advice raising a bug report with them.
