### ISSUE TITLE
Accessing exposed method throws unexposed attribute error.

### ISSUE THREAD

**Issue by mickp** [irmen/Pyro4#178]
Running Pyro 4.60.
I have a class with methods
  setPower(self, arg)
  setPower_mW(self, arg)

If I try to access setPower_mW, it results in
  AttributeError: attempt to access unexposed attribute 'setPower_mW'
If I rename the method to setPowermW, behaviour is as expected - the remote method is called correctly.

**Comment by mickp** [comment]
`import Pyro4
import threading
import time


class Thing(object):
    @Pyro4.expose
    def doStuff(self):
        return 123
    
    @Pyro4.expose
    def setA(self, arg):
        return arg
        
    @Pyro4.expose
    def setA_B(self, arg):
        return self.setPower(arg)

myThing = Thing()

host='127.0.0.1'
port=8000
daemon = Pyro4.Daemon(port=int(port), host=host)
# Start the daemon in a new thread.
daemon_thread = threading.Thread(
        target=Pyro4.Daemon.serveSimple,
        args = ({myThing: 'obj'},), # our mapping of class instances to names
        kwargs = {'daemon': daemon, 'ns': False}
        )
daemon_thread.start()
time.sleep(1)

l = Pyro4.Proxy("PYRO:obj@%s:%s" % (host, port))
l.setA_B(10)`

**Comment by mickp** [comment]
```python
import Pyro4
import threading
import time


class Thing(object):
    @Pyro4.expose
    def doStuff(self):
        return 123
    
    @Pyro4.expose
    def setA(self, arg):
        return arg
        
    @Pyro4.expose
    def setA_B(self, arg):
        return self.setPower(arg)

myThing = Thing()

host='127.0.0.1'
port=8000
daemon = Pyro4.Daemon(port=int(port), host=host)
# Start the daemon in a new thread.
daemon_thread = threading.Thread(
        target=Pyro4.Daemon.serveSimple,
        args = ({myThing: 'obj'},), # our mapping of class instances to names
        kwargs = {'daemon': daemon, 'ns': False}
        )
daemon_thread.start()
time.sleep(1)

l = Pyro4.Proxy("PYRO:obj@%s:%s" % (host, port))
l.setA_B(10)
```

**Comment by mickp** [comment]
My bad - a parent class is wrapping the exposed method and buggering up the name, somehow.

**Comment by irmen** [comment]
thanks for following up
