### ISSUE TITLE
Pyro4 test suite fails with Travis

### ISSUE THREAD

**Issue by Peque** [irmen/Pyro4#180]
From time to time it seems to fail.

Seems to be the same problem always, but with different results:

- [All tests pass, but the build is terminated by Travis as it gets stuck](https://travis-ci.org/irmen/Pyro4/jobs/254797980).
- [All tests pass, the build success but there is still an error in the Travis log](https://travis-ci.org/irmen/Pyro4/jobs/254797983).
- [`testInvalidMessageCrash` fails and the usual log appears](https://travis-ci.org/Peque/Pyro4/jobs/254950452).
- [`testInvalidMessageCrash` fails but this time with no other log](https://travis-ci.org/irmen/Pyro4/jobs/254950478)
- [`testInvalidMessageCrash` fails and this time with extra log](https://travis-ci.org/irmen/Pyro4/jobs/254955673)

They seem to occur randomly, independently from the Python interpreter version.

**Comment by irmen** [comment]
The concurrent jobs limit was set to 1 but I didn't think much of it. What is a travis build job exactly? Anyway I've cranked it up a bit to 4 to see if that helps.  Other transiet build errors such as "invalid message type X received" also pop up now and then, no idea where these come from. Same solution: retry build and often it then works.... 🤔

**Comment by Peque** [comment]
@irmen Yeah, I don't think that could help with this issue. A job is each of the Travis configurations to run the tests (in Pyro4 case is just all the supported Python interpreters):

![](http://i.imgur.com/K4xSctZ.png)

Allowing concurrent builds (free plans let you run at most 5 concurrent build jobs) will simply make tests finish faster. So the only advantage is that you will see Travis results faster.

**Comment by irmen** [comment]
I tweaked the test_socket.py tests a little and things seem better now https://travis-ci.org/irmen/Pyro4/builds/261651597

**Comment by irmen** [comment]
Closing this issue now, I've seen a couple of travis builds run without errors now, while previously at least one of the tasks would fail.

Re-open if you disagree or if travis starts playing up again 😄
