### ISSUE TITLE
Add an option to run flame in firejail

### ISSUE THREAD

**Issue by traverseda** [irmen/Pyro4#183]
https://firejail.wordpress.com/

This looks like it would allow you to use flame safely. Also puns.

**Comment by irmen** [comment]
Why should we add this option in Pyro itself? Isn't it as simple as running:

    $ PYRO_FLAME_ENABLED=1 firejail python3 -m Pyro4.utils.flameserver

(or something like that)

**Comment by traverseda** [comment]
Hmm, looks like. I'll give it a shot.

**Comment by irmen** [comment]
The pun is a good one though

**Comment by traverseda** [comment]
Once I finish my current thing I'll try using firejail, and do a PR to add it to the documentation.

**Comment by irmen** [comment]
closing this issue for now then.
