### ISSUE TITLE
Remote module attributes are inaccessible using Flame

### ISSUE THREAD

**Issue by LevyCory** [irmen/Pyro4#188]

**Comment by LevyCory** [comment]
When using Pyro Flame, there’s no option to access module attributes that are not methods.

For example, after running the following code:

os_module = flame.module(“os”)
os_module.name

It returns a _RemoteMethod object and there is no way to extract the value out of it.

Thanks!

**Comment by irmen** [comment]
Hm, you're right, the module proxy that Flame provides doesn't expose attributes directly.
However there is an easy alternative: ``flame.evaluate``:

```
>>> flame=Pyro4.utils.flame.connect("localhost:38527")
>>> flame.evaluate("os.name")
'posix'
```

I'll mention this fact in the docs.

I don't have the intention to change things about flame anymore (for a future Pyro5, it will not be included at all), so I hope the above workaround works for you. If not, please let me know why.
