### ISSUE TITLE
Refcounting autoproxy unique UID's for automatic GC/unregistration requests

### ISSUE THREAD

**Issue by mccullerlp** [irmen/Pyro4#192]
I'm using Pyro4 to develop some bindings into python from Matlab and the AUTOPROXY is quite nice for keeping python computations and objects server-side and returning basic data like arrays. 

What would be quite useful is to use the Daemon proxy to allow requests for server-side unregistration as the client uses and then forgets about proxies. 

Essentially some way for the proxy to know when its URI was generated uniquely from a uuid, and then a __del__ method on the proxy that checks how many proxies remain with the same URI. If no others remain, then it can make a request to the server to free the object associated with the URI.

This would allow long-running servers while using AUTOPROXY and keeping objects entirely server-side. This is of course not possible with multiple clients sharing proxy's.

**Comment by irmen** [comment]
Hmm, I never fancied the idea to add automatic distributed garbage collection to Pyro.

But I have two questions:
1. have you looked at the resource-tracking feature (since Pyro 4.63)?  https://github.com/irmen/Pyro4/tree/master/examples/resourcetracking
1. can you explain a bit more how your setup looks like? Is Matlab running a Pyro server, or is it calling into a separately running Pyro server?  How is it doing the Pyro calls, does it have an embedded python?

**Comment by mccullerlp** [comment]
Sure, I can imagine since it has a lot of edge cases and is not to be taken lightly by users.

For Matlab, there is indeed an embedded interpreter. It turns out that it works very well with numpy, but breaks many libraries and cannot directly use scipy. Enter Pyro. Now I proxy the objects that perform computations and return only arrays, dictionaries and more proxies.

The Matlab object system is almost as dynamic as Python's, so I can wrap the Proxy objects themselves in a matlab class to address some shortcomings of the embedded python interface.

I am also using objects with dynamic attributes,  so the "expose" system isn't quite effective for the objects I am trying to wrap. 

Altogether, the binding system I am using adds two additional wrappers, one "SuperProxy" on the python side and one on the Matlab side. MetaProxy is probably a better name now that I am writing this.

The Python SuperProxy holds any type of python object and has method calls to forward into the object for attribute access and method calling. This circumvents the "expose" system and furthermore allows the SuperProxy to wrap/unwrap inputs and outputs to method calls and attribute gets/sets with more SuperProxy's. This captures my entire functionality within SuperProxy objects. I only need to expose a single factory and anything interfaced through Pyro is either plain data or proxied objects.

The MatlabProxy uses the forwarding methods instead of the usual direct calls. Matlab also does refcounting and so its destructor can inform the Daemon which objects may be collected (using the pyrosuper_done method below).

Here is the SuperProxy if you are interested. I will link you to the final library when it is released.

```python
"""
"""
from __future__ import division, print_function, unicode_literals
from declarative.utilities.future_from_2 import unicode, str
import Pyro4
import numpy as np
import numbers


class NeedsSubSuper(Exception):
    pass


@Pyro4.expose
class SuperProxy(object):
    #these are used for garbage collection
    protect = False
    done    = False

    def __init__(
            self,
            daemon,
            obj,
            register = True,
            protect  = None,
    ):
        self.daemon = daemon

        if isinstance(register, (str, unicode)):
            self.uri = self.daemon.register(self, register)
            if protect is None:
                protect = True
        elif register:
            #automatic registration!
            self.uri = self.daemon.register(self)

            if protect is None:
                protect = False
        else:
            self.uri = None
            if protect is None:
                protect = False

        #only assign in the rare event of True
        if protect:
            self.protect = protect

        self.obj = obj
        return

    def pyrosuper_getattr(self, name):
        val = getattr(self.obj, name)
        return self.pyrosuper_wrap(val)

    def pyrosuper_setattr(self, name, val):
        unval = self.pyrosuper_unwrap(val)
        return setattr(self.obj, name, unval)

    def pyrosuper_getitem(self, idx):
        val = self.obj[idx]
        return self.pyrosuper_wrap(val)

    def pyrosuper_setitem(self, idx, val):
        unval = self.pyrosuper_unwrap(val)
        self.obj[idx] = unval
        return

    def pyrosuper_call(self, name, *args, **kwargs):
        if name is None:
            val = self.obj
        else:
            val = getattr(self.obj, name)
        unargs = self.pyrosuper_unwrap(args)
        unkwargs = self.pyrosuper_unwrap(kwargs)
        ret = val(*unargs, **unkwargs)
        return self.pyrosuper_wrap(ret)

    def pyrosuper_done(self):
        if not self.protect and self.done:
            raise RuntimeError("done set twice!")
        self.done = True

    def pyrosuper_wrap(self, obj, throw = False):
        """
        throw causes an exception instead of creating a sub SuperProxy
        """
        if isinstance(obj, np.ndarray):
            return obj
        elif isinstance(obj, numbers.Number):
            return obj
        elif isinstance(obj, list):
            try:
                sublist = [self.pyrosuper_wrap(o, throw = True) for o in obj]
            except NeedsSubSuper:
                if throw:
                    raise
                else:
                    return SuperProxy(self.daemon, obj)
            else:
                return sublist
        elif isinstance(obj, tuple):
            try:
                subtup = tuple((self.pyrosuper_wrap(o, throw = True) for o in obj))
            except NeedsSubSuper:
                if throw:
                    raise
                else:
                    return SuperProxy(self.daemon, obj)
            else:
                return subtup
        elif isinstance(obj, dict):
            try:
                subdict = dict()
                for k, v in obj.items():
                    subdict[k] = self.pyrosuper_wrap(v, throw = True)
            except NeedsSubSuper:
                if throw:
                    raise
                else:
                    return SuperProxy(self.daemon, obj)
            else:
                return subdict
        if throw:
            raise NeedsSubSuper()

        return SuperProxy(self.daemon, obj)

    def pyrosuper_unwrap(self, obj):
        """
        throw causes an exception instead of creating a sub SuperProxy
        """
        if isinstance(obj, list):
            sublist = [self.pyrosuper_unwrap(o) for o in obj]
            return sublist
        elif isinstance(obj, tuple):
            subtup = tuple((self.pyrosuper_unwrap(o) for o in obj))
            return subtup
        elif isinstance(obj, dict):
            subdict = dict()
            for k, v in obj.items():
                subdict[k] = self.pyrosuper_unwrap(v)
            return subdict
        elif isinstance(obj, SuperProxy):
            return obj.obj
        elif isinstance(obj, Pyro4.Proxy):
            uri = obj._pyroUri
            uri = str(uri)
            name, loc = uri.split('@')
            if not name.startswith('PYRO:'):
                raise RuntimeError("Proxy unwrapping can't recognize proxy")
            name = name[5:]
            obj = self.daemon.objectsById[name]
            if isinstance(obj, SuperProxy):
                return obj.obj
            else:
                return obj
        else:
            return obj
```

**Comment by irmen** [comment]
I think you should already have the tools to make this happen:
- ``@behavior`` decorator to tell Pyro how to deal with instances
- the resource tracking feature I pointed out above
- the daemon will free resources if the socket connection (=proxy) gets disconnected.
- you could perhaps hook up your pyrosuper_done method to the *daemon* object itself and call its methods. It is possible to create a custom daemon interface (see the 'interface' parameter to the Daemon class's init method) that provides additional methods you can call.

I'm not willing to add the complexity of a built-in distributed garbage collector/refcounter to Pyro at this time.
