### ISSUE TITLE
-k is a local security hole

### ISSUE THREAD

**Issue by tkorvola** [irmen/Pyro4#199]
`argv` is public information on Unix systems: if `pyro4-ns` is started with the `-k` option, any local user can see the key with `ps`. Reading the key from a file would be more secure. For extra security, check that the key file is accessible only by the current user.

**Comment by irmen** [comment]
thank you, I'll think about a better implementation

**Comment by tkorvola** [comment]
Not totally sure about environment variables, but probably safe.

**Comment by irmen** [comment]
Note that using 2-way SSL is the better alternative if you're concerned about security anyway.

I think I will be marking the use of the -k command line option a run time deprecation warning as well
