### ISSUE TITLE
RPM specs for Pyro (including serpent)

### ISSUE THREAD

**Issue by pevogam** [irmen/Pyro4#204]
Hi Irmen,

We have some Python 2 and 3 compatible RPM spec files for both serpent and Pyro4 (should be easy enough to adapt for 5). Do you have a packaging folder where you accept such files that might be helpful for to people packaging Pyro? If you want them we can contribute them so that there are official RPMs for RHEL-based systems rather than everybody rewriting them on their own.

Plamen

**Comment by irmen** [comment]
The contrib/ directory looks like the place for this.

How does this compare to just running ``python setup.py bdist_rpm`` ?  I get a noarch and a src rpm out of that just nicely.

**Comment by pevogam** [comment]
I see, that's a good point. Custom spec files might require more maintenance in the end so the setuptools approach probably fits better.
