### ISSUE TITLE
Auto Proxy doesn't maintain async mode

### ISSUE THREAD

**Issue by MadcowD** [irmen/Pyro4#220]
If you are using auto proxy and set a proxy for a class to be async and that class has methods which return instances of other classes those instance proxies are not async.

Is this a bug, or a feature? If it is a feature there should be some documentation :)

**Comment by MadcowD** [comment]
Note this happens when you set the initial calss to async by using
```
InstanceManager._pyroAsync
```

**Comment by irmen** [comment]
It probably is a feature. The async mode is strictly per-proxy.  I agree this should be documented.

Note that in the next Pyro version (Pyro5) async proxies have gone the way of the dodo in favor of a  user code solution such as using Python's futures explicitly
