### ISSUE TITLE
isinstance and issubclass via a pyro proxy

### ISSUE THREAD

**Issue by carandraug** [irmen/Pyro4#221]
We make heavy use of python's abstract base classes to test whether a class provides a particular interface. This is performed via the builtin `isinstance` and `issubclass` functions. Obviously, this does not work if called on the proxy object.

Could there be a `_pyroX` method that would return the class of the remote object? To enable something like:

    isinstance(proxy._pyroRemoteClass, MyABC)

**Comment by irmen** [comment]
Interesting.

It's a new feature though. I'll think about a way to possibly add this to Pyro5 first.  Will you be using that? Or are you strictly on Pyro4?

**Comment by carandraug** [comment]
We're still Pyro4 only. We'll be working around this for now, by exposing an `isX` exposed method on the exposed class.

**Comment by irmen** [comment]
You could expose a property as well

**Comment by carandraug** [comment]
> You could expose a property as well

That will not work for our case. And thinking better, my suggestion on the first comment would also not work for us. The issue we have is that the system where the proxy is, is incapable of representing the class of the remote object. Even importing the module where the remote object class is defined would fail.

But I guess that even if this existed in Pyro4 and could be done on the remote object side, some people would have classes that can't be represented on the remote side.

**Comment by irmen** [comment]
Yeah, comparison is only possible by name. 
Also, there's the problem of semantics.  The proxy _is not_ equivalent to the remote class if you scrutinize it beyond a certain level. Still, I can imagine knowing a few bits of meta data about the remote class could be useful

**Comment by irmen** [comment]
@carandraug would a property with the name of the class (as a string) be useful at all?

**Comment by carandraug** [comment]
For my purposes, getting the name of the class would not be very useful. I already got a solution but I think it's specific to our use-case and not much use to Pyro. I explain the solution for my use case at the end of the comment though.  First, here's some thoughts I had about this since I opened this issue.

Let's consider this class:

    BaseFoo --> FooX

The proxy side has the class `BaseFoo`. The proxy side does not have `FooX`. `FooX` type can only exist on the server (the issue is not only the server can have instances of `FooX`, the issue is that the type can only exist on the server). We have a proxy for `FooX` instance and want to know:

    isinstance(proxy, BaseFoo)

1. Getting the class of the proxy from the server would not work because that class does not exist on the proxy side at all.

    ```
    # fails because proxy_type is not available
    isintance(proxy_type, BaseFoo)
    ```

2. Getting a string with the class name could work if we only wanted to match the string names. But since we are dealing with subclasses, then comparing strings would not work.

    ```
    # fails because proxy_type_name is "FooX" and not "BaseFoo"
    proxy_type_name == BaseFoo.__class__.__name__
    ```

3. Something that could work would be a property with the class MRO, and the client could do the comparison to the whole list. But this is getting messy. And it's getting messy even before addressing that the class name is not enough, we would need the fully qualified name.

It might cleaner to have a function that tries the comparison on the server side:

    Pyro4.proxy_of_instance(proxy, BaseFoo)

And this even works if the class does not exist on the server side. If this

    Pyro4.proxy_of_instance(proxy, BaseBar)

errors on the server because there is no `BaseBar` class on the server side, then the server wouldn't be able to serve such instance in the first place.

Not sure how this would behave if the proxy is a proxy for another pyro proxy though :/

----

Anyway, for our specific case, we have something like this:

```
Device ----> CameraDevice ---> IDSCamera
        |                 |--> AndorAtmcd
        |                 ---> Ximea
        |
        |--> LaserDevice ----> Omicron
                           --> Coherent
```

While the remote has the `CameraDevice` and `LaserDevice` classes, it does not have the `Ximea` class because that's dependent on having the actual camera software. What we need to ask, is whether a specific proxy, is proxy for a camera or laser.

What we are trying to do now, is have a metaclass where we overload `__instancecheck__` so that `isintance` checks whether the instance has a specific list of attributes. We already use ABCMeta has the metaclass, so now we change it a bit more so that it checks if the abstract methods are available on the proxy too.

    isintance(proxy, CameraDevice)

checks if proxy has the same attributes that we expect on a `CameraDevice` instead of the default behaviour of checking the types, which gives us client code that looks the same as if it wasn't using a proxy at all.

**Comment by irmen** [comment]
Interesting thoughs.

However. What about using the name server's metadata to provide this information for you?
So, rather than requesting a proxy by a specific URI, or name, you use the name server's yellow pages lookup to give you a proxy to an object having the metadata properties that you want.

You don't really care what exact class it is, as long as it has the properties. (much like Python's duck typing)
See the https://github.com/irmen/Pyro4/tree/master/examples/ns-metadata example

**Comment by irmen** [comment]
I'm closing this for now. I think a solution that doesn't depend on checking the class hierarchy in the client code is a more robust one hence the suggestion to try out the metadata feature of the naming server to get an object that has the required properties in the first place, and work from there without having to check its type further.
