### ISSUE TITLE
PyroError "invalid uri" when using a unix socket with spaces in the file path

### ISSUE THREAD

**Issue by SamSchott** [irmen/Pyro4#222]
When creating a daemon with a unix socket that has spaces in its file path, such as "/Users/samschott/Library/Application Support/myapp/myapp.sock" on macOS, registering a Pyro4 object fails with an "invalid uri" error.

This seems to happen because the regex which parses the uri does not allow whitespace in the location string. Is this behaviour intended or a bug?

**Comment by irmen** [comment]
I think there's no real reason not to allow spaces in the path.  So I'll treat it as a bug .

**Comment by SamSchott** [comment]
Thanks for the quick response (and fix) time!
