### ISSUE TITLE
Pyro4 instance_mode="single" but creating multiple instances of the object

### ISSUE THREAD

**Issue by Arun4rangan** [irmen/Pyro4#230]
I registered an object with :

```
@Pyro4.expose
@Pyro4.behavior(instance_mode="single")
class Animals(object):
    def __init__(self):
        print("Called")
```

Called it with serveSimple:
```
Pyro4.Daemon.serveSimple(
        {Animals: PYRO_ANIMAL_APP_NAME},
        ns=True,
        verbose=False,
        host="localhost",
    )
```

This results in :
```
called
called
```

Does pyro4 expects animal object to be a singleton? or is it taken care of when we specify `instance_mode="single"`?

**Comment by irmen** [comment]
No, the instance mode 'single' makes Pyro take care to create the object only once.

Your output is not reproducible behavior (I see just one "Called" being printed at all times)  There has to be something else going on in your code.  

What Pyro version are you using? Have you tried the 'instancemode' examples that come with Pyro?

**Comment by Arun4rangan** [comment]
I do have a Gunicorn which tries to access animals instance :
```
workers = min(cpu_count(), 4)
timeout = 300
preload_app = True


def on_starting(server):
    animals = Proxy("PYRONAME:" + PYRO_DECODER_APP_NAME)

    while True:
        try:
            animals.wait_till_ready()
            break
        except NamingError:
            pass
```
I have : Pyro4 (4.78)

Since there is no lock on: https://github.com/irmen/Pyro4/blob/9fd891c1cf33530cd263f83ed7f805317474a48c/src/Pyro4/core.py#L1535-L1543

Wouldn't there be a chance that multiple calls to pyro-ns result in multiple initialization of `animals` if animals take a long time to be created ( ie __init__ in animals take a long time) ?

**Comment by irmen** [comment]
Hmm.
If this proves to be an issue, I will perhaps not fix it in Pyro4 but only in Pyro5.

**Comment by irmen** [comment]
This was a fairly trivial fix actually, thanks for reporting
