### ISSUE TITLE
Proxy Count / Performance Monitoring

### ISSUE THREAD

**Issue by itsshavar** [irmen/Pyro4#233]
Hi,
I am not able to find any app or method to monitor the pyro4 app. Please support. If we could count atleast number of proxies getting generated every min.

**Comment by irmen** [comment]
Sorry, not going to happen in Pyro4 (feature frozen).  New feature requests should go to Pyro5.

However, I'm not going to implement any of this as the requirements are way too vague and broad, and there's a plethora of monitoring software tools.  So if you want to monitor things, you'll have to roll your own:

You can enable debug log mode and look in the logfile perhaps? https://github.com/irmen/Pyro4/blob/79de6434259ff82d202090cbd0901673d4b8344b/src/Pyro4/core.py#L1541 
Or perhaps subclass the Daemon class and monkeypatch some methods in it to handle your monitoring requirements.
Or maybe you can inspect the _pyroInstances  property of the deamon.
