### ISSUE TITLE
Support for Python 3.10?

### ISSUE THREAD

**Issue by gcsideal** [irmen/Pyro4#241]
Officially Python 3.10 is not supported and indeed it has at least one problem. Reported for Debian [1], self-testing fails with:
FAIL: testClassmethodExposeWrongOrderFail (test_util.TestMetaAndExpose)
Traceback (most recent call last):
  File "/[PKGBUILDDIR]/tests/PyroTests/test_util.py", line 375, in testClassmethodExposeWrongOrderFail
    with self.assertRaises(AttributeError) as ax:
AssertionError: AttributeError not raised

The actual line of code is this [2].

[1] https://bugs.debian.org/1002330
[2] https://github.com/irmen/Pyro4/blob/4.81/tests/PyroTests/test_util.py#L375

**Comment by irmen** [comment]
We just merged a pull request that fixes this today

**Comment by gcsideal** [comment]
> We just merged a pull request that fixes this today

Checked in the morning and didn't see newer commits. I do confirm, 62ec858c424037045f0fa8b1ce618e1abd7e1f3c fixes this.

**Comment by irmen** [comment]
@gcsideal I've just released a 4.82 version of Pyro4.  Note that the same Python 3.10 issue was present in Pyro5, which saw a new release as well to fix this.
