### ISSUE TITLE
How to execute multi clients concurrently?

### ISSUE THREAD

**Issue by Bigwode** [irmen/Pyro4#244]
```server.py
@Pyro4.behavior(instance_mode="percall")
class Server(object):
    @Pyro4.expose
    def printHello(self):
        output = "hello world!"
        print(output, 1, flush=True)
        time.sleep(10)
        print(output, 2, flush=True)
        time.sleep(10)
        print(output, 3, flush=True)
```
I run multi client, but I got 1,2,3, 1,2,3...  I want it execute multi clients concurrently, what should I do?
I tried to replace "percall" to "single" and "session" but it does not work.

**Comment by irmen** [comment]
Instance mode has nothing to do with concurrency.

Concurrency is achieved via multiple independent proxy connections.

https://pyro5.readthedocs.io/en/latest/servercode.html#server-types-and-concurrency-model

**Comment by irmen** [comment]
closing this. Feel free to reopen if you have more questions!
