### ISSUE TITLE
request: multiple processes providing the same object

### ISSUE THREAD

**Issue by houseofsuns** [irmen/Pyro4#36]
I'm trying pyro for a project of mine and thought that the following may be a nice feature: Allow multiple processes to provide the same pyro object.

My use case is the following: I have a web application which has a pretty typical separation of python-frontend, python-backend, postgresql-database. The python code is stateless and so it would be nice to simply run several processes to get around the GIL. Thus the frontend would access a pyro-backend object and would transparently get one from an arbitrary process which provides them allowing for parallelization and load balancing without effort.

**Comment by oneup7** [comment]
Hi @irmen . I know this is an old thread, but I'm curious if you have any examples of the ideas you mentioned in your comment? I'm looking for a way to register multiple remote objects of the same type.
Thanks!
