### ISSUE TITLE
How to solve 'Don't know how to serialize class <type 'numpy.ndarray>   ?

### ISSUE THREAD

**Issue by teknosains** [irmen/Pyro4#43]
I ran a script that has a numpy array with Pyro4 and got that error, I googled and found that i needed to set export=PYRO_SERIALIZER = pickle 

I ran it again but got different error : Pyro4.errors.NamingError : Failed to locate the namserver

that's weird as the server is running just fine

i changed export=PYRO_SERIALIZER = json , new errors : Pyro4.errors.ConnectionClosedError : receiving: not enough data

**Comment by XDGFX** [comment]
For anyone else who stumbles across this, the paragraph mentioned is now here: https://pyro4.readthedocs.io/en/stable/tipstricks.html#pyro-and-numpy

**Comment by irmen** [comment]
Also, the Pyro5 equivalent of that documentation page is here https://pyro5.readthedocs.io/en/latest/tipstricks.html?highlight=numpy#pyro-and-numpy
