### ISSUE TITLE
Flame with 'datetime.datetime.now'

### ISSUE THREAD

**Issue by alexsilva** [irmen/Pyro4#69]
The current implementation of Flame failure when the package has more than one level. 
For example: 'datetime.datetime'

The error prevents the use of the function 'now'

```
class Flame(object):
...
    def module(self, name):
        """import a module on the server given by the module name and returns a proxy to it"""
        if importlib:
            importlib.import_module(name)
        else:
            __import__(name)
        return FlameModule(self, name)
```

Below is an implementation that can help in this case:

```
class Flame(Pyro4.utils.flame.Flame):
...
    def module(self, name):
        packages = name.split('.')

        package = __import__(packages[0])
        modules = [package] + packages[1:]

        sys.modules[name] = reduce(lambda a, b: getattr(a, b, a), modules)

        return Pyro4.utils.flame.FlameModule(self, name)
```

**Comment by irmen** [comment]
What exactly is the error you're getting? What is your code? What do you expect to happen?

Please answer these questions because as far as I'm concerned it works:

```
$ python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import Pyro4
>>> Pyro4.config.SERIALIZER='pickle'
>>> import Pyro4.utils.flame
>>> flame=Pyro4.utils.flame.connect("localhost:49370")
>>> dt=flame.module("datetime")
>>> dt.datetime.now()
datetime.datetime(2015, 1, 5, 22, 56, 12, 290521)
>>>
```

**Comment by alexsilva** [comment]
1 datetime is de package.
2 datetime is the module.
3 now is the function.

I expect this:

dt=flame.module("datetime.datetime")
dt.now()

Try using the java client you will understand why. In my case with the Lua client, your example does not apply.

local nameserver = NameServer:new(constants.FLAME_NAME, 'python2014')

local px = Proxy:new(nameserver:getURI())
px:set_hmac(nameserver.hmac_key)

px.module({'datetime'}).date({2015, 1, 2})
px.module({'datetime.datetime'}).now()

**Comment by irmen** [comment]
I kinda suspect where this is going now, but
it really saves me a lot of time trying to reproduce a problem when you provide the actual and exact error message you're getting.

**Comment by alexsilva** [comment]
import error.

**Comment by irmen** [comment]
..... that is not an exact error.  Paste it including the stack trace please.

**Comment by irmen** [comment]
Also, why do you expect this to work? The normal python import mechanism doesn't work like that too:
```
>>> import datetime.datetime
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'datetime.datetime'; 'datetime' is not a package
```

**Comment by alexsilva** [comment]
Correct is

from datetime import datetime

Dynamic  way

dt = __import__('datetime', fromlist = ['datetime'])
datetime  = getattr(dt, 'datetime')


Wrong

import datetime.datetime
