### ISSUE TITLE
Yellow page service on name server.

### ISSUE THREAD

**Issue by mortlind** [irmen/Pyro4#85]
Extend the name server with a feature for adding metadata, e.g. a list of strings, for registered URIs. This could be used for supporting a yellow page service along with the naming service. One immediate use is to register the object type with the object URIs; which potentially may be performed automatically at the client side. The name server may then provide a method as "get_objects_of_category(cat)" returning a list of URIs for objects registered with the queried category in "cat".

**Comment by irmen** [comment]
I'm proposing the following API.
It is backwards compatible with the existing name server API.
It allows you to register a set of strings as metadata for entries in the NS.
You can get this set back in queries.
You can use the regular list method on the ns to filter on a subset of metadata strings.

```python
ns = Pyro4.naming.NameServer(storageProvider=self.storageProvider)
# register some names with metadata, and perform simple lookups
ns.register("meta1", "PYRO:meta1@localhost:1111", metadata={"a", "b", "c"})
ns.register("meta2", "PYRO:meta2@localhost:2222", metadata={"x", "y", "z"})
uri = ns.lookup("meta1")
self.assertEqual("meta1", uri.object)
uri, metadata = ns.lookup("meta1", return_metadata=True)
self.assertEqual("meta1", uri.object)
self.assertSetEqual({"a", "b", "c"}, metadata)
uri = ns.lookup("meta2")
self.assertEqual("meta2", uri.object)
uri, metadata = ns.lookup("meta2", return_metadata=True)
self.assertEqual("meta2", uri.object)
self.assertSetEqual({"x", "y", "z"}, metadata)
# get a list of everything, without and with metadata
reg = ns.list()
self.assertDictEqual({'meta1': 'PYRO:meta1@localhost:1111', 'meta2': 'PYRO:meta2@localhost:2222'}, reg)
reg = ns.list(return_metadata=True)
uri1, meta1 = reg["meta1"]
uri2, meta2 = reg["meta2"]
self.assertEqual("PYRO:meta1@localhost:1111", uri1)
self.assertSetEqual({"a", "b", "c"}, meta1)
self.assertEqual("PYRO:meta2@localhost:2222", uri2)
self.assertSetEqual({"x", "y", "z"}, meta2)
# filter on metadata subset
reg = ns.list(metadata={"a", "c"}, return_metadata=True)
self.assertEqual(1, len(reg))
uri1, meta1 = reg["meta1"]
self.assertEqual("PYRO:meta1@localhost:1111", uri1)
self.assertSetEqual({"a", "b", "c"}, meta1)
reg = ns.list(metadata={"a", "wrong"}, return_metadata=True)
self.assertEqual({}, reg)
reg = ns.list(metadata={"a", "b", "c", "wrong"}, return_metadata=True)
self.assertEqual({}, reg)
```

**Comment by irmen** [comment]
This API has been available in master for a while now btw

**Comment by mortlind** [comment]
I have not had the time to test this out yet, but it looks very good from a distance! One improvement could be some search logic, where you now have an implicit "and" among the metadata items in your search with "ns.list(metadata= ... ". This should not be for completeness, but as a facility.

**Comment by irmen** [comment]
Will see if I can come up with an easy way to at least have an "or" as well.

**Comment by irmen** [comment]
Added a ``metadata_any`` argument to ``ns.list()`` in 4b69a15e10782f35c219f9b7d3339b1f299ba4e7 that allows you to specify any metadata terms the registration shoud have (OR rather than the AND when using the ``metadata`` filter argument).

**Comment by mortlind** [comment]
This sounds good. I suggest a rename to symmetrical method name: .metadata() -> .metadata_all() ?

**Comment by irmen** [comment]
That makes sense

**Comment by mortlind** [comment]
If we are both happy about the resolution of this "issue", do you want me to close it? Or would you rather leave it open, until you find it complete and I have taken som time for testing?

**Comment by irmen** [comment]
It's fine if you close it once you've decided it will work for your code, I'll leave it open until then.

**Comment by irmen** [comment]
``metadata`` argument has been renamed to ``metadata_all`` in bd23a87a6ce026212e1fed7f3b1d5d19ad13f3ab
See also the updated ns-metadata example
