### ISSUE TITLE
examples/stdinstdout does not work

### ISSUE THREAD

**Issue by bart2** [irmen/Pyro4#89]
When trying to run sample code from examples/stdinstdout, following error is thrown:

    $ python program.py 
    uri of the remote i/o server, or enter for local i/o:PYRO:example.inputoutput.manager@localhost:38641
    'PYRO:example.inputoutput.manager@localhost:38641'
    Replacing sys.stdin and sys.stdout. Read and type on the server :-)
    Traceback (most recent call last):
      File "program.py", line 46, in <module>
        main()
      File "program.py", line 34, in main
        print("---remote interaction starts---")
      File "/usr/lib/python2.7/site-packages/Pyro4/core.py", line 247, in __getattr__
        self._pyroGetMetadata()
      File "/usr/lib/python2.7/site-packages/Pyro4/core.py", line 543, in _pyroGetMetadata
        self.__pyroCreateConnection()
      File "/usr/lib/python2.7/site-packages/Pyro4/core.py", line 511, in __pyroCreateConnection
        self.__processMetadata(handshake_response["meta"])
      File "/usr/lib/python2.7/site-packages/Pyro4/core.py", line 568, in __processMetadata
        raise errors.PyroError("remote object doesn't expose any methods or attributes")
    PyroError: remote object doesn't expose any methods or attributes

**Comment by irmen** [comment]
I *think* this particular example broke quite a few versions ago already, in 4.27, when I started enforcing not exposing "private" attributes. Will investigate further.

**Comment by bart2** [comment]
So, is there any other way to attach to a remote stdin/stdout with Pyro4?

**Comment by irmen** [comment]
I don't know what pexpect interact is. Maybe you could have a look at the Flame console and see if that somehow fits your needs?  See the flame example and https://pythonhosted.org/Pyro4/api/flame.html#Pyro4.utils.flame.Flame.console

**Comment by bart2** [comment]
https://pexpect.readthedocs.org/en/stable/api/pexpect.html#pexpect.spawn.interact
Can I connect with Flame console to a process started on a remote machine? For example first launch "ftp" utility and then use Flame console to execute commands in that FTP session?

**Comment by irmen** [comment]
No, only to a flame server instance which is a pyro server. If you launch an ftp session from within there you might be able to control it, but I fail to see what Pyro is of use then.

**Comment by zmrow** [comment]
I'm curious about this as well.  Is there any way to redirect stdin/out from remote?  I'd like to do interactive processes on a remote machine?  Flame probably is not an option for me.  The documentation mentions redirecting stdio but I haven't seena good example of redirecting stdin.

**Comment by irmen** [comment]
Where in the documentation is io redirection mentioned?
