### ISSUE TITLE
TypeError: get_fortune() missing 1 required positional argument: 'name' ?

### ISSUE THREAD

**Issue by rsm-imap-cc** [irmen/Pyro4#91]
Hello, I'm having some problems to update my programs from python2 to 3 and I wanted to ask for some help.

When I try to use the first example: (daemon.py)
```
import Pyro4

class GreetingMaker(object):
    def get_fortune(self, name):
        return "Hello, {0}. Here is your fortune message:\n" \
               "Behold the warranty -- the bold print giveth and the fine print taketh away.".format(name)

daemon = Pyro4.Daemon()                # make a Pyro daemon
uri = daemon.register(GreetingMaker)   # register the greeting maker as a Pyro object

print("Ready. Object uri =", uri)      # print the uri so we can use it in the client later
daemon.requestLoop()                   # start the event loop of the server to wait for calls
```

and (client.py)
```
import Pyro4

uri = input("What is the Pyro uri of the greeting object? ").strip()
name = input("What is your name? ").strip()

greeting_maker = Pyro4.Proxy(uri)         # get a Pyro proxy to the greeting object
print(greeting_maker.get_fortune(name))   # call method normally
```

When I try the client, I get the following error:
```
python3 client
What is the Pyro uri of the greeting object? PYRO:obj_31c67fb35ffe4048bd7bb01a8a30d02b@localhost:52730
What is your name? test
Traceback (most recent call last):
  File "client", line 10, in <module>
    print(greeting_maker.get_fortune(name))   # call method normally
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 160, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib/python3/dist-packages/Pyro4/core.py", line 318, in _pyroInvoke
    raise data
TypeError: get_fortune() missing 1 required positional argument: 'name'
```

Is this a problem from Pyro4, or I'm skipping something? Thanks for the help!

**Comment by irmen** [comment]
The code as posted is correct and works fine on my machine. I suspect the uri that you pasted in the client, is not pointing at the correct server object. Have you started the daemon.py first and copied the uri that it printed? Did you perhaps make a mistake earlier in daemon.py and forgot to run the corrected version afterwards? Also, what OS, python version, and Pyro version are you using?

**Comment by rsm-imap-cc** [comment]
Yep, daemon.py was running and I copy passed the right uri. ( I know the basics of py core since I use it in like 4 of my programs).

I'm running it over Debian Jessie, python 3.4.2,  and It seems that I have installed pyro4 and python3-pyro4 from the official Debian Jessie repositories.

Is it maybe because I'm already runing pyro for python 2.7?

**Comment by irmen** [comment]
Perhaps. Without any other info it's impossible to say what's wrong about your setup. Start eliminating factors. Make sure you run only python3, use the same pyro version, enable logging and have a look at the logfiles, etc etc. 
Also, Debian's packaging of Pyro4 is of a horribly outdated version. I strongly suggest removing it and installing a recent Pyro version (4.39 for instance) using pip. It could very well be that your issue has been fixed in one of the more recent pyro versions.

**Comment by rsm-imap-cc** [comment]
I tried by killing all my programs that was already using pyro (over 2.7) and it worked. Do you have the same problem? It would be nice to find a solution because I won't be able to do anything if the user is already using some program with pyro for 2.7

**Comment by rsm-imap-cc** [comment]
It just worked even if I had a running pyro with python 2.7.  ( I ignore why it is now working ). The only thing of what I'm sure is that I was calling the program with python3, because otherwise it can not import pyro4

**Comment by irmen** [comment]
Run your python 2.7 pyro programs on a different port, and you won't have issues.

**Comment by irmen** [comment]
also, with the current Pyro4 version it is possible to run the client with python3 and a server with python2 (not the other way around though). Closing this
