### ISSUE TITLE
Handle interrupted system calls in multiplex poll loop

### ISSUE THREAD

**Issue by jonhoo** [irmen/Pyro4#92]
If a process receives a signal while [waiting](https://github.com/irmen/Pyro4/blob/master/src/Pyro4/socketserver/multiplexserver.py#L170) in the polling multiplexing server, the resulting exception will cause the server to crash, instead of the exception being swallowed and the loop continuing as in the [select implementation](https://github.com/irmen/Pyro4/blob/master/src/Pyro4/socketserver/multiplexserver.py#L219).

**Comment by irmen** [comment]
note that the select server also crashes if the loopCondition is still true.
The exception swallowing only occurs when the server is shutting down and the loopCondition is no longer true, and when during that event the select/poll call raises an error.
Is this what you meant?

**Comment by jonhoo** [comment]
Ah, yes, sorry, you're right. At the very least, the two implementations should behave the same, though it might be correct for the server loop to *always* swallow signal exceptions? Or for that behavior to be configurable?

**Comment by irmen** [comment]
in commit a1a669c83846a3448b609a8e53f4b140caab47cb the poll loop now behaves the same as the select one.

I'm not sure why you would want to continue the loop if an error occurs?  Can we determine if it is transient (and continuing the loop makes sense)?

**Comment by jonhoo** [comment]
Well, continuing the loop may make sense if the process receives, say, `SIGUSR1`, which is not fatal to the process. I suppose the application developer could just wrap the invocation of the Pyro4 loop in a loop of their own, but this also seems error-prone. The developer now needs to know what exceptions that could be raised from inside Pyro4 are fatal, and which are not.

**Comment by irmen** [comment]
is there an easy way to classify the myriad of possible signals as fatal or non fatal?

**Comment by jonhoo** [comment]
I think the correct way to deal with this is to continue if the returned error is a `EINTR`, and die otherwise. If something like a `SIGSEGV` comes along, the program will crash regardless.

**Comment by irmen** [comment]
I've found this problematic to reproduce, but I still like to do so because I want to test a possible change before committing on it.  Any ideas?

**Comment by irmen** [comment]
Hm, there's actually a PEP dealing with this issue: https://www.python.org/dev/peps/pep-0475/
Furthermore, it seems that this PEP was accepted into Python 3.5: http://bugs.python.org/issue23285
 / https://github.com/python/cpython/commit/147beb2e371cd2cb6dc43e8bb16b20b955475c83

So I'm not going to add a very extensive workaround in Pyro, rather I suggest upgrading to Python 3.5 instead (which fixes EINTR handling on many more systemcalls and not only select)

If you're on Python 3.4 there's the InterruptedError exception which conveniently lets me catch a EINTR condition and I'll implement that around the select and poll calls.
