### ISSUE TITLE
AutoRelease flag globally and on specific proxies.

### ISSUE THREAD

**Issue by mortlind** [irmen/Pyro4#94]
One mittigation of exhausted thread-pool in a threaded daemon may be setting a configuration flag in  Pyro4.config telling proxies to always release their connection after each invocation (At the end in Pyro4.core.Proxy._pyroInvoke). This will slow down execution but will provide great flexibility in applications that are not performance-demanding.

Naturally such an option should also be configurable on indivividual proxy objects.

I can test this in a branch, if desired.

**Comment by irmen** [comment]
can you not just increase the thread pool size or switch to the multiplex server?

**Comment by mortlind** [comment]
I have not investigated how Pyro uses the thread pool. If all threads are allocate, it may take up considerable resources. But if it is dynamic, up AND down in size, it makes sense to put it to the maximum allowed by the stack size or system maximum number of threads. Based on your answer, I suppose the thread pool is dynamic, and not only growing.

**Comment by irmen** [comment]
No, it isn't. Currently the thread allocation is static, and you're right that this consumes resources

**Comment by irmen** [comment]
This is taken care of in other issues such as #82  and #108
