### ISSUE TITLE
URI uses __slots__, unnecessarily(?). 

### ISSUE THREAD

**Issue by marvingreenberg** [irmen/Pyro4#96]
Mostly just a question - I have a json serializer using __dict__ and common introspections assume that objects have __dict__, but this failed when URI is implemented with __slots__.  I can fix that simply enough.  But references like http://stackoverflow.com/questions/472000/python-slots suggest __slots__ should only be used when saving space is really important.  Is this optimization that critical?  
Thanks.

**Comment by irmen** [comment]
It probably isn't. I'll have a look at what happens when I remove it.

For now, you could perhaps use Pyro's internal serialization mechanism instead (which adds some hooks so you can also serialize Pyro classes into json and pickle and serpent). For instance:

```
>>> import Pyro4
>>> import Pyro4.util
>>> x=Pyro4.URI("PYRO:sdfdsf@localhost:5555")
>>> Pyro4.util.get_serializer("json").dumps(x)
b'{"__class__": "Pyro4.core.URI", "state": ["PYRO", "sdfdsf", null, "localhost", 5555]}'
>>>
```

**Comment by marvingreenberg** [comment]
Thanks for the response.  This is a minor issue, I already worked around it.   I just was trying to improve the code base (if it IS an improvement ;) ).
