### ISSUE TITLE
Name Server running on a Unix Socket cannot be accessed from a Pyro Server

### ISSUE THREAD

**Issue by mkmoisen** [irmen/Pyro4#98]
Please see my attached pull request for the details: https://github.com/irmen/Pyro4/pull/97

Also, is there a repo for Pyro4 version 4.34 (the last version that Jython was officially supported)? I saw the branch for 4.31, but couldn't find one for 4.34.

**Comment by mkmoisen** [comment]
Also, is there a repo for Pyro4 version 4.34 (the last version that Jython was officially supported)? I saw the branch for 4.31, but couldn't find one for 4.34.

**Comment by irmen** [comment]
Ignore the branches in my repo. I suggest you clone it and create a branch in your own repo then, from the 4.34 label  https://github.com/irmen/Pyro4/releases/tag/4.34
