### ISSUE TITLE
Per-call thread execution in server object to avoid circular lock.

### ISSUE THREAD

**Issue by mortlind** [irmen/Pyro4#99]
Currently in the "thread" server type, any circular call chain without a "oneway" in the chain between repeated objects, will lock down. This is, supposedly, caused by a "one thread per object"-model in the daemon.

Implement a per-call-model for associating threads from the thread pool to server objects registered to the daemon, such that circular call-chains only locks down when normal thread-safing and data protection would do so in a non-distributed implementation.

**Comment by irmen** [comment]
This is not strictly true or complete; the thread is not locked to an object in the daemon, rather, it's bound to a single proxy on the client. 

That being said, could you perhaps use the ``instance_mode`` argument to ``@expose()`` to tweak the way Pyro creates object instances in the Daemon? Depending on your code this may or may not help avoiding locking issues.

See  https://pythonhosted.org/Pyro4/servercode.html?highlight=instance_mode#pyro-daemon-publishing-pyro-objects

**Comment by mortlind** [comment]
I only assumed this happened on the server side. Is my case of lockup due to the same proxy involved in the chain, and not the same object in the daemon? E.g. if main -> pA -> pB -> pA was replaced by main -> p0A -> pB -> p1A, there would be no lockup, since object B has it's own proxy on A? Then if B was involved twice, calling p1A circularly, it would lock up again, right?

**Comment by irmen** [comment]
Yes, sounds about right. Also see the code and readme of the 'deadlock' example.

**Comment by mortlind** [comment]
OK. Thanks for that clarification, and sorry for not investigating thoroughly.

It seems that applying a principle of creating a new proxy for every call will rid us from any kind of circular lockup in the threaded model. Is that so?

**Comment by irmen** [comment]
If you leave your own server-side or client-side code out of the equation, I think so, yes.   Until you use up all threads in the threadpool -- then creating a new proxy will probably fail or freeze until a thread will be available again.    You can increase the number of threads in the pool.

**Comment by irmen** [comment]
While I would like to see improvements regarding the possible deadlock situation, it's not feasible at the moment to change anything about the proxy model. So I'm closing this.

Note that a guaranteed deadlock only occurs when you use a proxy again while it is still busy with an ongoing request. This happens when you reuse it in a callback scenario, and is quite easily avoided.
